/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author laure
 */
public class dataPanel extends javax.swing.JPanel {

    /**
     * Creates new form dataMenu
     */
    
    private Menu menuUtama;
    
    public dataPanel(Menu menuUtama) {
        initComponents();
        this.menuUtama = menuUtama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petugas_Panel = new javax.swing.JPanel();
        petugas_Label = new javax.swing.JLabel();
        petugasbtn_Label = new javax.swing.JLabel();
        line_panelRound3 = new Pallete.PanelRound();
        buku_Panel = new javax.swing.JPanel();
        buku_Label = new javax.swing.JLabel();
        bukubtn_Label1 = new javax.swing.JLabel();
        line_panelRound2 = new Pallete.PanelRound();
        anggota_Panel = new javax.swing.JPanel();
        anggota_Label = new javax.swing.JLabel();
        anggotabtn_Label = new javax.swing.JLabel();
        line_panelRound1 = new Pallete.PanelRound();
        dashboard_Panel = new javax.swing.JPanel();
        computer_Label = new javax.swing.JLabel();
        dashboardbtn_Label = new javax.swing.JLabel();
        line_panelRound = new Pallete.PanelRound();
        data_Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        petugas_Panel.setBackground(new java.awt.Color(255, 255, 255));

        petugas_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gravity-ui_person.png"))); // NOI18N

        petugasbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        petugasbtn_Label.setText("PETUGAS");
        petugasbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petugasbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petugasbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petugasbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound3.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound3Layout = new javax.swing.GroupLayout(line_panelRound3);
        line_panelRound3.setLayout(line_panelRound3Layout);
        line_panelRound3Layout.setHorizontalGroup(
            line_panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound3Layout.setVerticalGroup(
            line_panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout petugas_PanelLayout = new javax.swing.GroupLayout(petugas_Panel);
        petugas_Panel.setLayout(petugas_PanelLayout);
        petugas_PanelLayout.setHorizontalGroup(
            petugas_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petugas_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(petugas_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(petugasbtn_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        petugas_PanelLayout.setVerticalGroup(
            petugas_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(petugas_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(petugasbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buku_Panel.setBackground(new java.awt.Color(255, 255, 255));

        buku_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lets-icons_book (1).png"))); // NOI18N

        bukubtn_Label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bukubtn_Label1.setText("BUKU");
        bukubtn_Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukubtn_Label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bukubtn_Label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bukubtn_Label1MouseExited(evt);
            }
        });

        line_panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound2.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound2Layout = new javax.swing.GroupLayout(line_panelRound2);
        line_panelRound2.setLayout(line_panelRound2Layout);
        line_panelRound2Layout.setHorizontalGroup(
            line_panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound2Layout.setVerticalGroup(
            line_panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buku_PanelLayout = new javax.swing.GroupLayout(buku_Panel);
        buku_Panel.setLayout(buku_PanelLayout);
        buku_PanelLayout.setHorizontalGroup(
            buku_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buku_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buku_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bukubtn_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buku_PanelLayout.setVerticalGroup(
            buku_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(buku_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(bukubtn_Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        anggota_Panel.setBackground(new java.awt.Color(255, 255, 255));

        anggota_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lets-icons_group (1).png"))); // NOI18N

        anggotabtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        anggotabtn_Label.setText("ANGGOTA");
        anggotabtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotabtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anggotabtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anggotabtn_LabelMouseExited(evt);
            }
        });

        line_panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound1.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound1Layout = new javax.swing.GroupLayout(line_panelRound1);
        line_panelRound1.setLayout(line_panelRound1Layout);
        line_panelRound1Layout.setHorizontalGroup(
            line_panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound1Layout.setVerticalGroup(
            line_panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout anggota_PanelLayout = new javax.swing.GroupLayout(anggota_Panel);
        anggota_Panel.setLayout(anggota_PanelLayout);
        anggota_PanelLayout.setHorizontalGroup(
            anggota_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anggota_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anggota_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anggotabtn_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        anggota_PanelLayout.setVerticalGroup(
            anggota_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(anggota_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(anggotabtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dashboard_Panel.setBackground(new java.awt.Color(255, 255, 255));

        computer_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gridicons_computer (1).png"))); // NOI18N

        dashboardbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dashboardbtn_Label.setText("DASHBOARD");
        dashboardbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRoundLayout = new javax.swing.GroupLayout(line_panelRound);
        line_panelRound.setLayout(line_panelRoundLayout);
        line_panelRoundLayout.setHorizontalGroup(
            line_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRoundLayout.setVerticalGroup(
            line_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboard_PanelLayout = new javax.swing.GroupLayout(dashboard_Panel);
        dashboard_Panel.setLayout(dashboard_PanelLayout);
        dashboard_PanelLayout.setHorizontalGroup(
            dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(computer_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dashboardbtn_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dashboard_PanelLayout.setVerticalGroup(
            dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(computer_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(dashboardbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        data_Label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        data_Label.setForeground(new java.awt.Color(102, 102, 102));
        data_Label.setText("DATA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(petugas_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buku_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anggota_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboard_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(data_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboard_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anggota_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buku_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petugas_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void petugasbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasbtn_LabelMouseClicked
        // TODO add your handling code here:
        petugas_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound3.setBackground(new Color(0, 0, 0));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuPetugas());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_petugasbtn_LabelMouseClicked

    private void petugasbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasbtn_LabelMouseEntered
        // TODO add your handling code here:
        petugas_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound3.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_petugasbtn_LabelMouseEntered

    private void petugasbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasbtn_LabelMouseExited
        // TODO add your handling code here:
        petugas_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_petugasbtn_LabelMouseExited

    private void bukubtn_Label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukubtn_Label1MouseClicked
        // TODO add your handling code here:
        buku_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound2.setBackground(new Color(0, 0, 0));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuBuku());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_bukubtn_Label1MouseClicked

    private void bukubtn_Label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukubtn_Label1MouseEntered
        // TODO add your handling code here:
        buku_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound2.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_bukubtn_Label1MouseEntered

    private void bukubtn_Label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukubtn_Label1MouseExited
        // TODO add your handling code here:
        buku_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bukubtn_Label1MouseExited

    private void anggotabtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotabtn_LabelMouseClicked
        // TODO add your handling code here:
        anggota_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound1.setBackground(new Color(0, 0, 0));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuAnggota());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_anggotabtn_LabelMouseClicked

    private void anggotabtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotabtn_LabelMouseEntered
        // TODO add your handling code here:
        anggota_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound1.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_anggotabtn_LabelMouseEntered

    private void anggotabtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotabtn_LabelMouseExited
        // TODO add your handling code here:
        anggota_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_anggotabtn_LabelMouseExited

    private void dashboardbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbtn_LabelMouseClicked
        // TODO add your handling code here:
        dashboard_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound.setBackground(new Color(0, 0, 0));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuDashboard());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_dashboardbtn_LabelMouseClicked

    private void dashboardbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbtn_LabelMouseEntered
        // TODO add your handling code here:
        dashboard_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_dashboardbtn_LabelMouseEntered

    private void dashboardbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbtn_LabelMouseExited
        // TODO add your handling code here:
        dashboard_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardbtn_LabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anggota_Label;
    private javax.swing.JPanel anggota_Panel;
    private javax.swing.JLabel anggotabtn_Label;
    private javax.swing.JLabel buku_Label;
    private javax.swing.JPanel buku_Panel;
    private javax.swing.JLabel bukubtn_Label1;
    private javax.swing.JLabel computer_Label;
    private javax.swing.JPanel dashboard_Panel;
    private javax.swing.JLabel dashboardbtn_Label;
    private javax.swing.JLabel data_Label;
    private Pallete.PanelRound line_panelRound;
    private Pallete.PanelRound line_panelRound1;
    private Pallete.PanelRound line_panelRound2;
    private Pallete.PanelRound line_panelRound3;
    private javax.swing.JLabel petugas_Label;
    private javax.swing.JPanel petugas_Panel;
    private javax.swing.JLabel petugasbtn_Label;
    // End of variables declaration//GEN-END:variables
}
