/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;

import Controller.LoginController;
import Model.UserModel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author laure
 */
public class LoginView extends javax.swing.JFrame {
    
    int xx, xy;
    private LoginController controller;

    /** Creates new form Login */
    public LoginView() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        closeeye_Label.setVisible(false);
        
        UserModel model = new UserModel();
        controller = new LoginController(this, model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Pallete.PanelRound();
        panelRound2 = new Pallete.PanelRound();
        img_Label = new javax.swing.JLabel();
        logo_Label = new javax.swing.JLabel();
        closebtn_Label = new javax.swing.JLabel();
        username_TextField = new javax.swing.JTextField();
        username_Label = new javax.swing.JLabel();
        welcome_Label = new javax.swing.JLabel();
        openeye_Label = new javax.swing.JLabel();
        closeeye_Label = new javax.swing.JLabel();
        pass_PasswordField = new javax.swing.JPasswordField();
        password_Label = new javax.swing.JLabel();
        login_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.setPreferredSize(new java.awt.Dimension(842, 488));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(255, 255, 204));
        panelRound2.setForeground(new java.awt.Color(255, 255, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(421, 100));
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopRight(20);

        img_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library-login-form.png"))); // NOI18N

        logo_Label.setBackground(new java.awt.Color(255, 255, 255));
        logo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (3).png"))); // NOI18N

        closebtn_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zondicons_close-solid (1).png"))); // NOI18N
        closebtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtn_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img_Label))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(logo_Label)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(closebtn_Label)
                        .addGap(15, 15, 15))))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(closebtn_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_Label)
                .addGap(57, 57, 57)
                .addComponent(img_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 448, 567));
        panelRound1.add(username_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 350, 40));

        username_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        username_Label.setForeground(new java.awt.Color(102, 102, 102));
        username_Label.setText("Username:");
        panelRound1.add(username_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 155, -1, -1));

        welcome_Label.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        welcome_Label.setForeground(new java.awt.Color(51, 51, 51));
        welcome_Label.setText("SELAMAT DATANG");
        panelRound1.add(welcome_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 90, -1, -1));

        openeye_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ph_eye (1).png"))); // NOI18N
        openeye_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openeye_LabelMouseClicked(evt);
            }
        });
        panelRound1.add(openeye_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        closeeye_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_eye-off-outline.png"))); // NOI18N
        closeeye_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeeye_LabelMouseClicked(evt);
            }
        });
        panelRound1.add(closeeye_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));
        panelRound1.add(pass_PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 271, 350, 40));

        password_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        password_Label.setForeground(new java.awt.Color(102, 102, 102));
        password_Label.setText("Password:");
        panelRound1.add(password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 246, -1, -1));

        login_Button.setBackground(new java.awt.Color(0, 51, 255));
        login_Button.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        login_Button.setForeground(new java.awt.Color(255, 255, 255));
        login_Button.setText("LOGIN");
        login_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_ButtonMouseClicked(evt);
            }
        });
        panelRound1.add(login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 90, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx , y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void login_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_ButtonMouseClicked
        // TODO add your handling code here:
        fireLoginEvent();
    }//GEN-LAST:event_login_ButtonMouseClicked

    private void openeye_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openeye_LabelMouseClicked
        // TODO add your handling code here:
        openeye_Label.setVisible(false);
        closeeye_Label.setVisible(true);
        pass_PasswordField.setEchoChar((char)0);
    }//GEN-LAST:event_openeye_LabelMouseClicked

    private void closeeye_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeeye_LabelMouseClicked
        // TODO add your handling code here:
        openeye_Label.setVisible(true);
        closeeye_Label.setVisible(false);
        pass_PasswordField.setEchoChar('*');
    }//GEN-LAST:event_closeeye_LabelMouseClicked

    private void closebtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtn_LabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closebtn_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closebtn_Label;
    private javax.swing.JLabel closeeye_Label;
    private javax.swing.JLabel img_Label;
    private javax.swing.JButton login_Button;
    private javax.swing.JLabel logo_Label;
    private javax.swing.JLabel openeye_Label;
    private Pallete.PanelRound panelRound1;
    private Pallete.PanelRound panelRound2;
    private javax.swing.JPasswordField pass_PasswordField;
    private javax.swing.JLabel password_Label;
    private javax.swing.JLabel username_Label;
    private javax.swing.JTextField username_TextField;
    private javax.swing.JLabel welcome_Label;
    // End of variables declaration//GEN-END:variables

    public String getUsername() {
        return username_TextField.getText();
    }

    public String getPassword() {
        return new String(pass_PasswordField.getPassword());
    }
    
    public boolean validasiInput(){
        boolean valid = false;
        if(username_TextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username tidak boleh kosong");
        } else if(pass_PasswordField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong");
        } else{
            valid = true;
        }
        return valid;
    }
    
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Pesan", JOptionPane.INFORMATION_MESSAGE);
    }

    public void addLoginListener(java.awt.event.ActionListener listener) {
        login_Button.addActionListener(listener);
    }

    private void fireLoginEvent() {
        for (java.awt.event.ActionListener listener : login_Button.getActionListeners()) {
            listener.actionPerformed(new java.awt.event.ActionEvent(this, java.awt.event.ActionEvent.ACTION_PERFORMED, null));
        }
    }

}
