/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
import java.sql.SQLException;
import java.text.ParseException;
import java.util.concurrent.TimeUnit;


/**
 *
 * @author laure
 */
public class menuPengembalian extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    private final Connection conn;
    private String userID;
    
    public menuPengembalian(String userID) {
        initComponents();
        
        conn = Koneksi.getConnection();
        this.userID = userID;
        detailpengembalian_Label.setVisible(false);
        jScrollPane4.setVisible(false);
        setTableModel();
        setTableModelDetail();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        viewpengembalian_mainPanel = new javax.swing.JPanel();
        viewpengembalian_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        riwayat_Table = new javax.swing.JTable();
        detailpengembalian_Label = new javax.swing.JLabel();
        menupengembalian_Label = new javax.swing.JLabel();
        pengembalian_Label = new javax.swing.JLabel();
        add_Label = new javax.swing.JLabel();
        add_Button = new javax.swing.JButton();
        delete_Label = new javax.swing.JLabel();
        cancel_Label = new javax.swing.JLabel();
        cancel_Button = new javax.swing.JButton();
        search_Label = new javax.swing.JLabel();
        search_TextField = new javax.swing.JTextField();
        datapengembalian_Label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        detail_Table = new javax.swing.JTable();
        viewpengembalian_addPanel = new javax.swing.JPanel();
        datapengembalian_Label1 = new javax.swing.JLabel();
        menupengembalian_Label2 = new javax.swing.JLabel();
        pengembalian_Label1 = new javax.swing.JLabel();
        save_Label = new javax.swing.JLabel();
        save_Button = new javax.swing.JButton();
        batal_Label = new javax.swing.JLabel();
        batal_Button = new javax.swing.JButton();
        idagt_Label = new javax.swing.JLabel();
        idagt_TextField = new javax.swing.JTextField();
        tglpinjam_Label = new javax.swing.JLabel();
        tglpinjam_TextField = new javax.swing.JTextField();
        tglkembali_Label = new javax.swing.JLabel();
        tglkembali_TextField = new javax.swing.JTextField();
        namaagt_Label = new javax.swing.JLabel();
        namaagt_TextField = new javax.swing.JTextField();
        panelRound1 = new Pallete.PanelRound();
        id_Label = new javax.swing.JLabel();
        id_TextField = new javax.swing.JTextField();
        tgl_Label = new javax.swing.JLabel();
        tglsekarang_TextField = new javax.swing.JTextField();
        peminjaman_Label = new javax.swing.JLabel();
        idpinjam_TextField = new javax.swing.JTextField();
        setpeminjamanButton = new javax.swing.JButton();
        penerbit_Label = new javax.swing.JLabel();
        penerbit_TextField = new javax.swing.JTextField();
        judul_Label = new javax.swing.JLabel();
        judul_TextField = new javax.swing.JTextField();
        pengarang_Label = new javax.swing.JLabel();
        pengarang_TextField = new javax.swing.JTextField();
        buku_Label = new javax.swing.JLabel();
        buku_TextField = new javax.swing.JTextField();
        total_Label = new javax.swing.JLabel();
        denda_Label = new javax.swing.JLabel();
        denda_Label1 = new javax.swing.JLabel();
        jumlah_Label = new javax.swing.JLabel();
        jumlah_TextField = new javax.swing.JTextField();

        dateChooser1.setTextRefernce(tglsekarang_TextField);

        setPreferredSize(new java.awt.Dimension(561, 480));
        setLayout(new java.awt.CardLayout());

        viewpengembalian_mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewpengembalian_mainPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewpengembalian_mainPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewpengembalian_mainPanel.setLayout(new java.awt.CardLayout());

        viewpengembalian_Panel.setBackground(new java.awt.Color(255, 255, 255));
        viewpengembalian_Panel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewpengembalian_Panel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewpengembalian_Panel.setPreferredSize(new java.awt.Dimension(561, 480));
        viewpengembalian_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riwayat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        riwayat_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayat_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(riwayat_Table);

        viewpengembalian_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 520, 130));

        detailpengembalian_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        detailpengembalian_Label.setText("Detail Pengembalian");
        viewpengembalian_Panel.add(detailpengembalian_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        menupengembalian_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menupengembalian_Label.setText("Pengembalian");
        viewpengembalian_Panel.add(menupengembalian_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        pengembalian_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lucide_book-up-2 (1).png"))); // NOI18N
        viewpengembalian_Panel.add(pengembalian_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        add_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_add.png"))); // NOI18N
        viewpengembalian_Panel.add(add_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        add_Button.setBackground(new java.awt.Color(0, 0, 0));
        add_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        add_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_Button.setText("       Tambah");
        add_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ButtonActionPerformed(evt);
            }
        });
        viewpengembalian_Panel.add(add_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        delete_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_delete-outline.png"))); // NOI18N
        viewpengembalian_Panel.add(delete_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 30));

        cancel_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewpengembalian_Panel.add(cancel_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 30));

        cancel_Button.setBackground(new java.awt.Color(255, 102, 0));
        cancel_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cancel_Button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_Button.setText("       Cancel");
        cancel_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });
        viewpengembalian_Panel.add(cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 30));

        search_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_search.png"))); // NOI18N
        viewpengembalian_Panel.add(search_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, 30));

        search_TextField.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        search_TextField.setText("Search");
        search_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_TextFieldKeyTyped(evt);
            }
        });
        viewpengembalian_Panel.add(search_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 520, 30));

        datapengembalian_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        datapengembalian_Label.setText("Data Pengembalian");
        viewpengembalian_Panel.add(datapengembalian_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        detail_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(detail_Table);

        viewpengembalian_Panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 520, 130));

        viewpengembalian_mainPanel.add(viewpengembalian_Panel, "card3");

        viewpengembalian_addPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewpengembalian_addPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewpengembalian_addPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewpengembalian_addPanel.setPreferredSize(new java.awt.Dimension(561, 480));
        viewpengembalian_addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datapengembalian_Label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        datapengembalian_Label1.setText("Tambah Pengembalian Buku");
        viewpengembalian_addPanel.add(datapengembalian_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        menupengembalian_Label2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menupengembalian_Label2.setText("Pengembalian");
        viewpengembalian_addPanel.add(menupengembalian_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        pengembalian_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lucide_book-up-2 (1).png"))); // NOI18N
        viewpengembalian_addPanel.add(pengembalian_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        save_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tdesign_save.png"))); // NOI18N
        viewpengembalian_addPanel.add(save_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        save_Button.setBackground(new java.awt.Color(0, 51, 255));
        save_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        save_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_Button.setText("       Simpan");
        save_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        save_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });
        viewpengembalian_addPanel.add(save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        batal_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewpengembalian_addPanel.add(batal_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 30));

        batal_Button.setBackground(new java.awt.Color(255, 102, 0));
        batal_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        batal_Button.setForeground(new java.awt.Color(255, 255, 255));
        batal_Button.setText("       Batal");
        batal_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        batal_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        batal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_ButtonActionPerformed(evt);
            }
        });
        viewpengembalian_addPanel.add(batal_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, 30));

        idagt_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        idagt_Label.setText("Anggota");
        viewpengembalian_addPanel.add(idagt_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        idagt_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        idagt_TextField.setForeground(new java.awt.Color(102, 102, 102));
        idagt_TextField.setText("ID Anggota");
        viewpengembalian_addPanel.add(idagt_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 20));

        tglpinjam_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tglpinjam_Label.setText("Peminjaman");
        viewpengembalian_addPanel.add(tglpinjam_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        tglpinjam_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        tglpinjam_TextField.setForeground(new java.awt.Color(102, 102, 102));
        tglpinjam_TextField.setText("Tanggal Peminjaman");
        viewpengembalian_addPanel.add(tglpinjam_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 20));

        tglkembali_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tglkembali_Label.setText("Pengembalian");
        viewpengembalian_addPanel.add(tglkembali_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        tglkembali_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        tglkembali_TextField.setForeground(new java.awt.Color(102, 102, 102));
        tglkembali_TextField.setText("Tanggal Pengembalian");
        viewpengembalian_addPanel.add(tglkembali_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 20));

        namaagt_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        namaagt_Label.setText("Nama Anggota");
        viewpengembalian_addPanel.add(namaagt_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        namaagt_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        namaagt_TextField.setForeground(new java.awt.Color(102, 102, 102));
        namaagt_TextField.setText("Nama Anggota");
        viewpengembalian_addPanel.add(namaagt_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 20));

        panelRound1.setBackground(new java.awt.Color(255, 204, 153));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        id_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        id_Label.setText("ID");

        id_TextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        id_TextField.setForeground(new java.awt.Color(102, 102, 102));
        id_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_TextField.setText("ID Pengembalian");

        tgl_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tgl_Label.setText("Tanggal");

        tglsekarang_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tglsekarang_TextField.setForeground(new java.awt.Color(102, 102, 102));
        tglsekarang_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(id_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(tgl_Label)
                .addGap(5, 5, 5)
                .addComponent(tglsekarang_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglsekarang_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tgl_Label)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        viewpengembalian_addPanel.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 520, 40));

        peminjaman_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        peminjaman_Label.setText("Peminjaman");
        viewpengembalian_addPanel.add(peminjaman_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        idpinjam_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        idpinjam_TextField.setForeground(new java.awt.Color(102, 102, 102));
        idpinjam_TextField.setText("ID Peminjaman");
        viewpengembalian_addPanel.add(idpinjam_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 20));

        setpeminjamanButton.setText("...");
        setpeminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setpeminjamanButtonActionPerformed(evt);
            }
        });
        viewpengembalian_addPanel.add(setpeminjamanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 20));

        penerbit_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        penerbit_Label.setText("Penerbit");
        viewpengembalian_addPanel.add(penerbit_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        penerbit_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        penerbit_TextField.setForeground(new java.awt.Color(102, 102, 102));
        penerbit_TextField.setText("Nama Penerbit");
        viewpengembalian_addPanel.add(penerbit_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 160, 20));

        judul_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        judul_Label.setText("Judul");
        viewpengembalian_addPanel.add(judul_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        judul_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        judul_TextField.setForeground(new java.awt.Color(102, 102, 102));
        judul_TextField.setText("Judul Buku");
        viewpengembalian_addPanel.add(judul_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, 20));

        pengarang_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pengarang_Label.setText("Pengarang");
        viewpengembalian_addPanel.add(pengarang_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        pengarang_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        pengarang_TextField.setForeground(new java.awt.Color(102, 102, 102));
        pengarang_TextField.setText("Nama Pengarang");
        viewpengembalian_addPanel.add(pengarang_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 20));

        buku_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buku_Label.setText("Buku");
        viewpengembalian_addPanel.add(buku_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        buku_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        buku_TextField.setForeground(new java.awt.Color(102, 102, 102));
        buku_TextField.setText("ID Buku");
        viewpengembalian_addPanel.add(buku_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, 20));

        total_Label.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        total_Label.setForeground(new java.awt.Color(255, 0, 0));
        total_Label.setText("TOTAL");
        viewpengembalian_addPanel.add(total_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 70, 50));

        denda_Label.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        denda_Label.setText("Info Denda");
        viewpengembalian_addPanel.add(denda_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        denda_Label1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        denda_Label1.setText("Total Denda");
        viewpengembalian_addPanel.add(denda_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jumlah_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jumlah_Label.setText("Jumlah");
        viewpengembalian_addPanel.add(jumlah_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jumlah_TextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jumlah_TextField.setForeground(new java.awt.Color(102, 102, 102));
        jumlah_TextField.setText("Jumlah Buku Kembali");
        viewpengembalian_addPanel.add(jumlah_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 160, 20));

        viewpengembalian_mainPanel.add(viewpengembalian_addPanel, "card3");

        add(viewpengembalian_mainPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        // TODO add your handling code here:
        viewpengembalian_mainPanel.removeAll();
        viewpengembalian_mainPanel.add(viewpengembalian_addPanel);
        viewpengembalian_mainPanel.repaint();
        viewpengembalian_mainPanel.revalidate();
        
        id_TextField.setText(setIDPengembalian());
        id_TextField.setEnabled(false);
        
        columnDisable();
    }//GEN-LAST:event_add_ButtonActionPerformed

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        // TODO add your handling code here:
        showPanel();
        loadData();
    }//GEN-LAST:event_cancel_ButtonActionPerformed

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
        // TODO add your handling code here:
        insertData();
        insertDataDetail();
        updateStatus();
        resetForm();
        loadData();
        showPanel();
    }//GEN-LAST:event_save_ButtonActionPerformed

    private void batal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_ButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar ?", "Batal", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            resetForm();
            viewpengembalian_mainPanel.removeAll();
            viewpengembalian_mainPanel.add(viewpengembalian_Panel);
            viewpengembalian_mainPanel.repaint();
            viewpengembalian_mainPanel.revalidate();
        }
    }//GEN-LAST:event_batal_ButtonActionPerformed

    private void riwayat_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayat_TableMouseClicked
        // TODO add your handling code here:
            cancel_Button.setVisible(true);
            detailpengembalian_Label.setVisible(true);
            
            jScrollPane4.setVisible(true);
            int row = riwayat_Table.getSelectedRow();
            String id = riwayat_Table.getValueAt(row, 0).toString();
            
            loadDataDetail(id);
    }//GEN-LAST:event_riwayat_TableMouseClicked

    private void search_TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_TextFieldKeyTyped
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_search_TextFieldKeyTyped

    private void setpeminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setpeminjamanButtonActionPerformed
        // TODO add your handling code here:
        getPeminjaman();
        hitungDenda();
    }//GEN-LAST:event_setpeminjamanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Button;
    private javax.swing.JLabel add_Label;
    private javax.swing.JButton batal_Button;
    private javax.swing.JLabel batal_Label;
    private javax.swing.JLabel buku_Label;
    private javax.swing.JTextField buku_TextField;
    private javax.swing.JButton cancel_Button;
    private javax.swing.JLabel cancel_Label;
    private javax.swing.JLabel datapengembalian_Label;
    private javax.swing.JLabel datapengembalian_Label1;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel delete_Label;
    private javax.swing.JLabel denda_Label;
    private javax.swing.JLabel denda_Label1;
    private javax.swing.JTable detail_Table;
    private javax.swing.JLabel detailpengembalian_Label;
    private javax.swing.JLabel id_Label;
    private javax.swing.JTextField id_TextField;
    private javax.swing.JLabel idagt_Label;
    private javax.swing.JTextField idagt_TextField;
    private javax.swing.JTextField idpinjam_TextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel judul_Label;
    private javax.swing.JTextField judul_TextField;
    private javax.swing.JLabel jumlah_Label;
    private javax.swing.JTextField jumlah_TextField;
    private javax.swing.JLabel menupengembalian_Label;
    private javax.swing.JLabel menupengembalian_Label2;
    private javax.swing.JLabel namaagt_Label;
    private javax.swing.JTextField namaagt_TextField;
    private Pallete.PanelRound panelRound1;
    private javax.swing.JLabel peminjaman_Label;
    private javax.swing.JLabel penerbit_Label;
    private javax.swing.JTextField penerbit_TextField;
    private javax.swing.JLabel pengarang_Label;
    private javax.swing.JTextField pengarang_TextField;
    private javax.swing.JLabel pengembalian_Label;
    private javax.swing.JLabel pengembalian_Label1;
    private javax.swing.JTable riwayat_Table;
    private javax.swing.JButton save_Button;
    private javax.swing.JLabel save_Label;
    private javax.swing.JLabel search_Label;
    private javax.swing.JTextField search_TextField;
    private javax.swing.JButton setpeminjamanButton;
    private javax.swing.JLabel tgl_Label;
    private javax.swing.JLabel tglkembali_Label;
    private javax.swing.JTextField tglkembali_TextField;
    private javax.swing.JLabel tglpinjam_Label;
    private javax.swing.JTextField tglpinjam_TextField;
    private javax.swing.JTextField tglsekarang_TextField;
    private javax.swing.JLabel total_Label;
    private javax.swing.JPanel viewpengembalian_Panel;
    private javax.swing.JPanel viewpengembalian_addPanel;
    private javax.swing.JPanel viewpengembalian_mainPanel;
    // End of variables declaration//GEN-END:variables

    private void setTableModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengembalian");
        model.addColumn("Tanggal Dikembalikan");
        model.addColumn("ID Peminjaman");
        model.addColumn("Nama Petugas");

        riwayat_Table.setModel(model);
    }
    
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) riwayat_Table.getModel();
        cancel_Button.setVisible(false);
        model.setRowCount(0);

        try {
            String sql = "SELECT ID_Pengembalian, Tanggal_Pengembalian, ID_Peminjaman, Nama_User "
                       + "FROM Pengembalian "
                       + "INNER JOIN User ON User.ID_User = Pengembalian.ID_User ";

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_Pengembalian"),
                    rs.getString("Tanggal_Pengembalian"),
                    rs.getString("ID_Peminjaman"),
                    rs.getString("Nama_User")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void resetForm() {
        id_TextField.setText("");
        tglsekarang_TextField.setText("");
        
        setpeminjamanButton.setEnabled(true);
        idpinjam_TextField.setText("ID Peminjaman");
        tglpinjam_TextField.setText("Tanggal Peminjaman");
        tglkembali_TextField.setText("Tanggal Pengembalian");
        idagt_TextField.setText("ID Anggota");
        namaagt_TextField.setText("Nama Anggota");
        
        buku_TextField.setText("ID Buku");
        judul_TextField.setText("Judul Buku");
        pengarang_TextField.setText("Nama Pengarang");
        penerbit_TextField.setText("Nama Penerbit");
        
        total_Label.setText("TOTAL");
    }
    
    private void showPanel(){
        viewpengembalian_mainPanel.removeAll();
        viewpengembalian_mainPanel.add(new menuPengembalian(userID));
        viewpengembalian_mainPanel.repaint();
        viewpengembalian_mainPanel.revalidate();
    }
    
    public String setIDPengembalian() {
        String urutan = null;
        Date now = new Date();
        SimpleDateFormat noFormat = new SimpleDateFormat("yyMM");
        String no = noFormat.format(now);
        
        String sql = "SELECT SUBSTR(ID_Pengembalian, 7, 4) AS Nomor " +
                     "FROM Pengembalian " +
                     "WHERE ID_Pengembalian LIKE 'PG" + no + "%' " +
                     "ORDER BY ID_Pengembalian DESC " +
                     "LIMIT 1";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            ResultSet rs = st.executeQuery();
            
            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("Nomor")) + 1;
                urutan = "PG" + no + String.format("%04d", nomor);
            } else {
                urutan = "PG" + no + "0001";
            }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(menuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        
        return urutan;
    }

    private void insertData() {
        String idPengembalian = id_TextField.getText();
        String tglSekarang = tglsekarang_TextField.getText();
        String idPeminjaman = idpinjam_TextField.getText();
        
        try {
            String sql = "INSERT INTO Pengembalian (ID_Pengembalian, Tanggal_Pengembalian, ID_Peminjaman, ID_User) VALUES (?,?,?,?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, idPengembalian);
                st.setString(2, tglSekarang);
                st.setString(3, idPeminjaman);
                st.setString(4, userID);

                int rowInserted = st.executeUpdate();
                if (rowInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                }
            }
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(menuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }
    
    private void insertDataDetail() {
        String idPengembalian = id_TextField.getText();
        String idBuku = buku_TextField.getText();
        String jmlDenda = total_Label.getText();
        String jmlKembali = jumlah_TextField.getText();
        
        try {
            String sql = "INSERT INTO Detail_Pengembalian (ID_Pengembalian, ID_Buku, Jumlah_Denda, Jumlah_Kembali) VALUES (?,?,?,?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, idPengembalian);
                st.setString(2, idBuku);
                st.setString(3, jmlDenda);
                st.setString(4, jmlKembali);
                
                st.executeUpdate();        
            } 
        }catch (SQLException e) {
            java.util.logging.Logger.getLogger(menuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }

    private void searchData() {
        String kakun = search_TextField.getText();
        
        DefaultTableModel model = (DefaultTableModel) riwayat_Table.getModel();
        model.setRowCount(0);

        try {
            String sql = "SELECT ID_Peminjaman, Tanggal_Peminjaman, Tanggal_Pengembalian, "
                       + "Total_Pinjam, Nama_User, Nama_Anggota "
                       + "FROM Peminjaman "
                       + "INNER JOIN User ON User.ID_User = Peminjaman.ID_User "
                       + "INNER JOIN Anggota ON Anggota.ID_Anggota = Peminjaman.ID_Anggota " 
                       + "WHERE ID_Peminjaman LIKE ? OR Nama_Anggota LIKE ? OR Tanggal_Peminjaman LIKE ? OR Tanggal_Pengembalian LIKE ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, "%" + kakun + "%");
            st.setString(2, "%" + kakun + "%");
            st.setString(3, "%" + kakun + "%");
            st.setString(4, "%" + kakun + "%");
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("ID_Peminjaman"), rs.getString("Tanggal_Peminjaman"), rs.getString("Tanggal_Pengembalian"), rs.getString("Total_Pinjam"), rs.getString("Nama_User"), rs.getString("Nama_Anggota")});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getPeminjaman() {
        boolean closeable = true;
        datapeminjaman_Dialog pinjam = new datapeminjaman_Dialog(null, closeable);
        pinjam.setVisible(true);
        
        idpinjam_TextField.setText(pinjam.getIdPeminjaman());
        tglpinjam_TextField.setText(pinjam.getTglPeminjaman());
        tglkembali_TextField.setText(pinjam.getTglPengembalian());
        idagt_TextField.setText(pinjam.getIdAnggota());
        namaagt_TextField.setText(pinjam.getNamaAnggota());
        buku_TextField.setText(pinjam.getIdBuku());
        judul_TextField.setText(pinjam.getJudulBuku());
        pengarang_TextField.setText(pinjam.getPengarangBuku());
        penerbit_TextField.setText(pinjam.getPenerbitBuku());
        jumlah_TextField.setText(pinjam.getJumlahBuku());
        
        idpinjam_TextField.setEnabled(false);
        tglpinjam_TextField.setEnabled(false);
        tglkembali_TextField.setEnabled(false);
        idagt_TextField.setEnabled(false);
        namaagt_TextField.setEnabled(false);
        buku_TextField.setEnabled(false);
        judul_TextField.setEnabled(false);
        pengarang_TextField.setEnabled(false);
        penerbit_TextField.setEnabled(false);
        jumlah_TextField.setEnabled(false);
    }

    private void columnDisable() {
        idpinjam_TextField.setEnabled(false);
        tglpinjam_TextField.setEnabled(false);
        tglkembali_TextField.setEnabled(false);
        idagt_TextField.setEnabled(false);
        namaagt_TextField.setEnabled(false);
        
        buku_TextField.setEnabled(false);
        judul_TextField.setEnabled(false);
        pengarang_TextField.setEnabled(false);
        penerbit_TextField.setEnabled(false);
        jumlah_TextField.setEnabled(false);
    }

    private void setTableModelDetail() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengembalian");
        model.addColumn("ID Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Jumlah Denda");
        
        detail_Table.setModel(model);
    }
    
    private void loadDataDetail(String id) {
        DefaultTableModel model = (DefaultTableModel) detail_Table.getModel();
        model.setRowCount(0);

        try {
            String sql = "SELECT ID_Pengembalian, Buku.ID_Buku, Judul_Buku, Jumlah_Denda "
                       + "FROM Detail_Pengembalian "
                       + "INNER JOIN Buku ON Buku.ID_Buku = Detail_Pengembalian.ID_Buku "
                       + "WHERE Detail_Pengembalian.ID_Pengembalian = '"+id+"'";

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ID_Pengembalian"),
                    rs.getString("ID_Buku"),
                    rs.getString("Judul_Buku"),
                    rs.getString("Jumlah_Denda")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateStatus() {
        String idPeminjaman = idpinjam_TextField.getText();
        String idBuku = buku_TextField.getText();
        String statusPeminjaman = "Sudah dikembalikan";
        
        try {
            String sql = "UPDATE Detail_Peminjaman SET Status_Peminjaman=? WHERE ID_Peminjaman=? AND ID_Buku=?";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, statusPeminjaman);
                st.setString(2, idPeminjaman);
                st.setString(3, idBuku);
                
                st.executeUpdate();        
            } 
        }catch (SQLException e) {
            java.util.logging.Logger.getLogger(menuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }

    private void hitungDenda() {
        int dendaperhari = 1000;
        String tglkembaliaktual = tglsekarang_TextField.getText();
        String tglkmbli = tglkembali_TextField.getText();

        try {
            // Menggunakan format yang sesuai dengan input
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            dateFormat.setLenient(false);  // Menolak tanggal yang tidak valid

            Date tglkembalisekarang = dateFormat.parse(tglkembaliaktual);
            Date tglkembali = dateFormat.parse(tglkmbli);

            // Hitung selisih hari
            long selisihMilidetik = tglkembalisekarang.getTime() - tglkembali.getTime();
            long selisihhari = TimeUnit.MILLISECONDS.toDays(selisihMilidetik);

            // Hitung denda
            int denda = (int) selisihhari * dendaperhari;

            if (selisihhari > 0) {
                denda_Label.setText("Telat: " + selisihhari + " hari");
                total_Label.setText(Integer.toString(denda));
            } else {
                denda_Label.setText("Pengembalian tepat waktu");
                total_Label.setText("0");
            }

        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
}
