/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.BukuController;
import Model.Buku;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author laure
 */
public class menuBuku extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    private BukuController controller;
    
    public menuBuku() {
        initComponents();
        
        Buku model = new Buku();
        controller = new BukuController(model);
        setTableModel(controller.getBukuTableModel());
        
        delete_Button.setVisible(false);
        cancel_Button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewbuku_mainPanel = new javax.swing.JPanel();
        viewbuku_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        riwayat_Table = new javax.swing.JTable();
        databuku_Label = new javax.swing.JLabel();
        menubuku_Label = new javax.swing.JLabel();
        buku_Label = new javax.swing.JLabel();
        add_Label = new javax.swing.JLabel();
        add_Button = new javax.swing.JButton();
        delete_Label = new javax.swing.JLabel();
        delete_Button = new javax.swing.JButton();
        cancel_Label = new javax.swing.JLabel();
        cancel_Button = new javax.swing.JButton();
        search_Label = new javax.swing.JLabel();
        search_TextField = new javax.swing.JTextField();
        viewbuku_addPanel = new javax.swing.JPanel();
        databuku_Label1 = new javax.swing.JLabel();
        menubuku_Label2 = new javax.swing.JLabel();
        buku_Label1 = new javax.swing.JLabel();
        save_Label = new javax.swing.JLabel();
        save_Button = new javax.swing.JButton();
        batal_Label = new javax.swing.JLabel();
        batal_Button = new javax.swing.JButton();
        id_Label = new javax.swing.JLabel();
        id_TextField = new javax.swing.JTextField();
        judul_Label = new javax.swing.JLabel();
        judul_TextField = new javax.swing.JTextField();
        pengarang_Label = new javax.swing.JLabel();
        pengarang_TextField = new javax.swing.JTextField();
        tahun_TextField = new javax.swing.JTextField();
        tahun_Label = new javax.swing.JLabel();
        kategori_Label = new javax.swing.JLabel();
        kategori_TextField = new javax.swing.JTextField();
        penerbit_Label = new javax.swing.JLabel();
        penerbit_TextField = new javax.swing.JTextField();
        stok_Label = new javax.swing.JLabel();
        stok_TextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(561, 480));
        setLayout(new java.awt.CardLayout());

        viewbuku_mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewbuku_mainPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewbuku_mainPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewbuku_mainPanel.setLayout(new java.awt.CardLayout());

        viewbuku_Panel.setBackground(new java.awt.Color(255, 255, 255));
        viewbuku_Panel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewbuku_Panel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewbuku_Panel.setPreferredSize(new java.awt.Dimension(561, 480));
        viewbuku_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riwayat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        riwayat_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayat_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(riwayat_Table);

        viewbuku_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 520, 310));

        databuku_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        databuku_Label.setText("Data Buku");
        viewbuku_Panel.add(databuku_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        menubuku_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menubuku_Label.setText("Buku");
        viewbuku_Panel.add(menubuku_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        buku_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lets-icons_book (1).png"))); // NOI18N
        viewbuku_Panel.add(buku_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        add_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_add.png"))); // NOI18N
        viewbuku_Panel.add(add_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        add_Button.setBackground(new java.awt.Color(0, 0, 0));
        add_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        add_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_Button.setText("       Tambah");
        add_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ButtonActionPerformed(evt);
            }
        });
        viewbuku_Panel.add(add_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        delete_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_delete-outline.png"))); // NOI18N
        viewbuku_Panel.add(delete_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 30));

        delete_Button.setBackground(new java.awt.Color(255, 0, 0));
        delete_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_Button.setText("       Hapus");
        delete_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });
        viewbuku_Panel.add(delete_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 30));

        cancel_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewbuku_Panel.add(cancel_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 30));

        cancel_Button.setBackground(new java.awt.Color(255, 102, 0));
        cancel_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cancel_Button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_Button.setText("       Cancel");
        cancel_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });
        viewbuku_Panel.add(cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, 30));

        search_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_search.png"))); // NOI18N
        viewbuku_Panel.add(search_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, 30));

        search_TextField.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        search_TextField.setText("Search");
        search_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_TextFieldKeyTyped(evt);
            }
        });
        viewbuku_Panel.add(search_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 520, 30));

        viewbuku_mainPanel.add(viewbuku_Panel, "card3");

        viewbuku_addPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewbuku_addPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewbuku_addPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewbuku_addPanel.setPreferredSize(new java.awt.Dimension(561, 480));
        viewbuku_addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databuku_Label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        databuku_Label1.setText("Tambah Data Buku");
        viewbuku_addPanel.add(databuku_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        menubuku_Label2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menubuku_Label2.setText("Buku");
        viewbuku_addPanel.add(menubuku_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        buku_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lets-icons_book (1).png"))); // NOI18N
        viewbuku_addPanel.add(buku_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        save_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tdesign_save.png"))); // NOI18N
        viewbuku_addPanel.add(save_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        save_Button.setBackground(new java.awt.Color(0, 51, 255));
        save_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        save_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_Button.setText("       Simpan");
        save_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        save_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });
        viewbuku_addPanel.add(save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        batal_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewbuku_addPanel.add(batal_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 30));

        batal_Button.setBackground(new java.awt.Color(255, 102, 0));
        batal_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        batal_Button.setForeground(new java.awt.Color(255, 255, 255));
        batal_Button.setText("       Batal");
        batal_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        batal_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        batal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_ButtonActionPerformed(evt);
            }
        });
        viewbuku_addPanel.add(batal_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 30));

        id_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        id_Label.setText("ID");
        viewbuku_addPanel.add(id_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        id_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        id_TextField.setForeground(new java.awt.Color(102, 102, 102));
        id_TextField.setText("ID Buku");
        viewbuku_addPanel.add(id_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 30));

        judul_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        judul_Label.setText("Judul");
        viewbuku_addPanel.add(judul_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        judul_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        judul_TextField.setForeground(new java.awt.Color(102, 102, 102));
        judul_TextField.setText("Judul Buku");
        viewbuku_addPanel.add(judul_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 240, 30));

        pengarang_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pengarang_Label.setText("Pengarang");
        viewbuku_addPanel.add(pengarang_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        pengarang_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pengarang_TextField.setForeground(new java.awt.Color(102, 102, 102));
        pengarang_TextField.setText("Pengarang Buku");
        viewbuku_addPanel.add(pengarang_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, 30));

        tahun_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tahun_TextField.setForeground(new java.awt.Color(102, 102, 102));
        tahun_TextField.setText("Tahun Terbit");
        viewbuku_addPanel.add(tahun_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 240, 30));

        tahun_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tahun_Label.setText("Tahun");
        viewbuku_addPanel.add(tahun_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        kategori_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        kategori_Label.setText("Kategori");
        viewbuku_addPanel.add(kategori_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        kategori_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kategori_TextField.setForeground(new java.awt.Color(102, 102, 102));
        kategori_TextField.setText("Kategori Buku");
        viewbuku_addPanel.add(kategori_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 30));

        penerbit_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        penerbit_Label.setText("Penerbit");
        viewbuku_addPanel.add(penerbit_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        penerbit_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        penerbit_TextField.setForeground(new java.awt.Color(102, 102, 102));
        penerbit_TextField.setText("Penerbit Buku");
        viewbuku_addPanel.add(penerbit_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, 30));

        stok_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        stok_Label.setText("Stok");
        viewbuku_addPanel.add(stok_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        stok_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stok_TextField.setForeground(new java.awt.Color(102, 102, 102));
        stok_TextField.setText("Stok Buku");
        viewbuku_addPanel.add(stok_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 240, 30));

        viewbuku_mainPanel.add(viewbuku_addPanel, "card3");

        add(viewbuku_mainPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        // TODO add your handling code here:
        id_TextField.setEnabled(false);
        viewbuku_mainPanel.removeAll();
        viewbuku_mainPanel.add(viewbuku_addPanel);
        viewbuku_mainPanel.repaint();
        viewbuku_mainPanel.revalidate();
        
        id_TextField.setText(controller.generateIDBuku());
        if(add_Button.getText().equals("      Perbarui")){
            dataTabel();
            save_Button.setText("      Perbarui");
        }
    }//GEN-LAST:event_add_ButtonActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = riwayat_Table.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus data ini ?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String id = riwayat_Table.getValueAt(selectedRow, 0).toString();
            if (controller.deleteBuku(id)) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
            }
        }
        resetForm();
        delete_Button.setVisible(false);
        cancel_Button.setVisible(false);
        showPanel();
    }//GEN-LAST:event_delete_ButtonActionPerformed

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        // TODO add your handling code here:
        showPanel();
        delete_Button.setVisible(false);
        cancel_Button.setVisible(false);
    }//GEN-LAST:event_cancel_ButtonActionPerformed

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
        // TODO add your handling code here:
        if (save_Button.getText() == "Tambah") {
            save_Button.setText("       Simpan");
        } else if (save_Button.getText() == "       Simpan") {
            insertData();
        } else if (save_Button.getText() == "      Perbarui") {
            updateData();
        }
    }//GEN-LAST:event_save_ButtonActionPerformed

    private void batal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_ButtonActionPerformed
        // TODO add your handling code here:
        viewbuku_mainPanel.removeAll();
        viewbuku_mainPanel.add(viewbuku_Panel);
        viewbuku_mainPanel.repaint();
        viewbuku_mainPanel.revalidate();
        resetForm();
    }//GEN-LAST:event_batal_ButtonActionPerformed

    private void riwayat_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayat_TableMouseClicked
        // TODO add your handling code here:
        if (add_Button.getText().equals("       Tambah")){
            add_Button.setText("      Perbarui");
            delete_Button.setVisible(true);
            cancel_Button.setVisible(true);
        }
            
    }//GEN-LAST:event_riwayat_TableMouseClicked

    private void search_TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_TextFieldKeyTyped
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_search_TextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Button;
    private javax.swing.JLabel add_Label;
    private javax.swing.JButton batal_Button;
    private javax.swing.JLabel batal_Label;
    private javax.swing.JLabel buku_Label;
    private javax.swing.JLabel buku_Label1;
    private javax.swing.JButton cancel_Button;
    private javax.swing.JLabel cancel_Label;
    private javax.swing.JLabel databuku_Label;
    private javax.swing.JLabel databuku_Label1;
    private javax.swing.JButton delete_Button;
    private javax.swing.JLabel delete_Label;
    private javax.swing.JLabel id_Label;
    private javax.swing.JTextField id_TextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul_Label;
    private javax.swing.JTextField judul_TextField;
    private javax.swing.JLabel kategori_Label;
    private javax.swing.JTextField kategori_TextField;
    private javax.swing.JLabel menubuku_Label;
    private javax.swing.JLabel menubuku_Label2;
    private javax.swing.JLabel penerbit_Label;
    private javax.swing.JTextField penerbit_TextField;
    private javax.swing.JLabel pengarang_Label;
    private javax.swing.JTextField pengarang_TextField;
    private javax.swing.JTable riwayat_Table;
    private javax.swing.JButton save_Button;
    private javax.swing.JLabel save_Label;
    private javax.swing.JLabel search_Label;
    private javax.swing.JTextField search_TextField;
    private javax.swing.JLabel stok_Label;
    private javax.swing.JTextField stok_TextField;
    private javax.swing.JLabel tahun_Label;
    private javax.swing.JTextField tahun_TextField;
    private javax.swing.JPanel viewbuku_Panel;
    private javax.swing.JPanel viewbuku_addPanel;
    private javax.swing.JPanel viewbuku_mainPanel;
    // End of variables declaration//GEN-END:variables

    private void setTableModel(DefaultTableModel model) {
        riwayat_Table.setModel(model);
    }
    
    private void resetForm() {
        judul_TextField.setText("Judul Buku");
        kategori_TextField.setText("Kategori Buku");
        pengarang_TextField.setText("Pengarng Buku");
        penerbit_TextField.setText("Penerbit Buku");
        tahun_TextField.setText("Tahun Terbit");
        stok_TextField.setText("Stok Buku");
    }
    
    private void showPanel(){
        viewbuku_mainPanel.removeAll();
        viewbuku_mainPanel.add(new menuBuku());
        viewbuku_mainPanel.repaint();
        viewbuku_mainPanel.revalidate();
    }
    
    private void insertData() {
        String idBuku = id_TextField.getText();
        String judulBuku = judul_TextField.getText();
        String kategoriBuku = kategori_TextField.getText();
        String pengarangBuku = pengarang_TextField.getText();
        String penerbitBuku = penerbit_TextField.getText();
        String tahunBuku = tahun_TextField.getText();
        String stokBuku = stok_TextField.getText();

        if (idBuku.isEmpty() || judulBuku.isEmpty() || kategoriBuku.isEmpty() || pengarangBuku.isEmpty() || penerbitBuku.isEmpty() || tahunBuku.isEmpty() || stokBuku.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom harus diisi !", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (controller.addBuku(idBuku, judulBuku, kategoriBuku, pengarangBuku, penerbitBuku, tahunBuku, stokBuku)) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
            resetForm();
            delete_Button.setVisible(false);
            cancel_Button.setVisible(false);
            showPanel();
        }
    }

    private void dataTabel() {
        viewbuku_Panel.setVisible(false);
        viewbuku_addPanel.setVisible(true);
        
        int row = riwayat_Table.getSelectedRow();
        databuku_Label1.setText("Perbarui Data Buku");
        
        id_TextField.setEnabled(false);
        
        id_TextField.setText(riwayat_Table.getValueAt(row, 0).toString());
        judul_TextField.setText(riwayat_Table.getValueAt(row, 1).toString());
        kategori_TextField.setText(riwayat_Table.getValueAt(row, 2).toString());
        pengarang_TextField.setText(riwayat_Table.getValueAt(row, 3).toString()); 
        penerbit_TextField.setText(riwayat_Table.getValueAt(row, 4).toString()); 
        tahun_TextField.setText(riwayat_Table.getValueAt(row, 5).toString());
        stok_TextField.setText(riwayat_Table.getValueAt(row, 6).toString());
    }

    private void updateData() {
        String idBuku = id_TextField.getText();
        String judulBuku = judul_TextField.getText();
        String kategoriBuku = kategori_TextField.getText();
        String pengarangBuku = pengarang_TextField.getText();
        String penerbitBuku = penerbit_TextField.getText();
        String tahunBuku = tahun_TextField.getText();
        String stokBuku = stok_TextField.getText();

        if (idBuku.isEmpty() || judulBuku.isEmpty() || kategoriBuku.isEmpty() || pengarangBuku.isEmpty() || penerbitBuku.isEmpty() || tahunBuku.isEmpty() || stokBuku.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom harus diisi !", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (controller.updateBuku(idBuku, judulBuku, kategoriBuku, pengarangBuku, penerbitBuku, tahunBuku, stokBuku)) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
            resetForm();
            delete_Button.setVisible(false);
            cancel_Button.setVisible(false);
            showPanel();
        }
    }

    private void searchData() {
        DefaultTableModel model = controller.searchBuku(search_TextField.getText());
        riwayat_Table.setModel(model);
    }
}
