/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;


/**
 *
 * @author laure
 */
public class menuPassword extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    private final Connection conn;
    private LoginView login;
    
    public menuPassword() {
        initComponents();
        
        conn = Koneksi.getConnection();
        login = new LoginView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewpetugas_mainPanel = new javax.swing.JPanel();
        viewpetugas_addPanel = new javax.swing.JPanel();
        datapetugas_Label1 = new javax.swing.JLabel();
        petugas_Label1 = new javax.swing.JLabel();
        save_Label = new javax.swing.JLabel();
        save_Button = new javax.swing.JButton();
        batal_Label = new javax.swing.JLabel();
        batal_Button = new javax.swing.JButton();
        username_Label = new javax.swing.JLabel();
        username_TextField = new javax.swing.JTextField();
        passlama_Label = new javax.swing.JLabel();
        passlama_PasswordField = new javax.swing.JPasswordField();
        passbaru_Label = new javax.swing.JLabel();
        passbaru_PasswordField = new javax.swing.JPasswordField();
        confirm_Label = new javax.swing.JLabel();
        confirm_PasswordField = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(561, 480));
        setLayout(new java.awt.CardLayout());

        viewpetugas_mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewpetugas_mainPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewpetugas_mainPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewpetugas_mainPanel.setLayout(new java.awt.CardLayout());

        viewpetugas_addPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewpetugas_addPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewpetugas_addPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewpetugas_addPanel.setPreferredSize(new java.awt.Dimension(561, 480));
        viewpetugas_addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datapetugas_Label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        datapetugas_Label1.setText("Pergantian Password");
        viewpetugas_addPanel.add(datapetugas_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        petugas_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vaadin_password.png"))); // NOI18N
        viewpetugas_addPanel.add(petugas_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        save_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tdesign_save.png"))); // NOI18N
        viewpetugas_addPanel.add(save_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        save_Button.setBackground(new java.awt.Color(0, 51, 255));
        save_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        save_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_Button.setText("       Simpan");
        save_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        save_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });
        viewpetugas_addPanel.add(save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        batal_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewpetugas_addPanel.add(batal_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 30));

        batal_Button.setBackground(new java.awt.Color(255, 102, 0));
        batal_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        batal_Button.setForeground(new java.awt.Color(255, 255, 255));
        batal_Button.setText("       Batal");
        batal_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        batal_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        batal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_ButtonActionPerformed(evt);
            }
        });
        viewpetugas_addPanel.add(batal_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 30));

        username_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        username_Label.setText("Username");
        viewpetugas_addPanel.add(username_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, -1));

        username_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        username_TextField.setForeground(new java.awt.Color(102, 102, 102));
        username_TextField.setText("Username");
        viewpetugas_addPanel.add(username_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 520, 30));

        passlama_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passlama_Label.setText("Password Lama");
        viewpetugas_addPanel.add(passlama_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        passlama_PasswordField.setText("jPasswordField1");
        viewpetugas_addPanel.add(passlama_PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 520, 30));

        passbaru_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passbaru_Label.setText("Password Baru");
        viewpetugas_addPanel.add(passbaru_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        passbaru_PasswordField.setText("jPasswordField1");
        viewpetugas_addPanel.add(passbaru_PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 520, 30));

        confirm_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        confirm_Label.setText("Konfirmasi Password Baru");
        viewpetugas_addPanel.add(confirm_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        confirm_PasswordField.setText("jPasswordField1");
        viewpetugas_addPanel.add(confirm_PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 520, 30));

        viewpetugas_mainPanel.add(viewpetugas_addPanel, "card3");

        add(viewpetugas_mainPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void batal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_ButtonActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_batal_ButtonActionPerformed

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
        // TODO add your handling code here:
        pergantianPass();
    }//GEN-LAST:event_save_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal_Button;
    private javax.swing.JLabel batal_Label;
    private javax.swing.JLabel confirm_Label;
    private javax.swing.JPasswordField confirm_PasswordField;
    private javax.swing.JLabel datapetugas_Label1;
    private javax.swing.JLabel passbaru_Label;
    private javax.swing.JPasswordField passbaru_PasswordField;
    private javax.swing.JLabel passlama_Label;
    private javax.swing.JPasswordField passlama_PasswordField;
    private javax.swing.JLabel petugas_Label1;
    private javax.swing.JButton save_Button;
    private javax.swing.JLabel save_Label;
    private javax.swing.JLabel username_Label;
    private javax.swing.JTextField username_TextField;
    private javax.swing.JPanel viewpetugas_addPanel;
    private javax.swing.JPanel viewpetugas_mainPanel;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        username_TextField.setText("Username");
        passlama_PasswordField.setText("Password");
        passbaru_PasswordField.setText("Passowrd");
        confirm_PasswordField.setText("Password");
    }

    private boolean validasiPass(String username, String password) {
        try{
            String sql = "SELECT * FROM User WHERE Username = ? AND Password = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            ResultSet rs = pstmt.executeQuery();
            return rs.next();
        } catch (SQLException ex){
            ex.printStackTrace();
            return false;
        }
    }
    
    private boolean pergantianPassword(String username, String passlama, String passbaru) {
        try{
            String sql = "SELECT * FROM User WHERE Username = ? AND Password = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, passlama);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                String sqlupdt = "UPDATE User SET Password = ? WHERE Username = ?";
                PreparedStatement pstmtupdt = conn.prepareStatement(sqlupdt);
                pstmtupdt.setString(1, passbaru);
                pstmtupdt.setString(2, username);
                int result = pstmtupdt.executeUpdate();
                return result > 0;
            } else{
                return false;
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            return false;
        }
    }

    private void pergantianPass() {
        String username = username_TextField.getText();
        String passlama = passlama_PasswordField.getText();
        String passbaru = passbaru_PasswordField.getText();
        String confirm = confirm_PasswordField.getText();
        
        if(!passbaru.equals(confirm)){
            JOptionPane.showMessageDialog(null, "Konfirmasi Password Baru Tidak Sesuai");
            return;
        }
        
        if(!validasiPass(username, passlama)){
            JOptionPane.showMessageDialog(null, "Username dan Password Lama Tidak Sesuai");
            return;
        }
        
        if(pergantianPassword(username, passlama, passbaru)){
            JOptionPane.showMessageDialog(null, "Password Berhasil Diubah");
        } else{
            JOptionPane.showMessageDialog(null, "Password Gagal Diubah");
        }
        resetForm();
    }
}
