/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author laure
 */
public class Menu extends javax.swing.JFrame {
    
    int xx, xy;
    private String userID;
    private String levelUser;
    private Timer time;
    
    /**
     * Creates new form Menu
     */
    
    public Menu(String userID, String namaUser, String levelUser) {
        initComponents();
        this.userID = userID;
        this.levelUser = levelUser;
        pfname_Label.setText(namaUser);
        addMenu();
        setDate();
    }
    
    public String getUserID(){
        return userID;
    }
    
    public String getLevelUser() {
        return levelUser;
    }
    
    public JPanel getPanelUtama(){
        return content_panelRound;
    }
    
    private void addMenu(){
        if(levelUser.equals("Admin")){
            sidemenu_Panel.add(new dataPanel(this));
            sidemenu_Panel.add(new transaksiPanel(this));
        }else{
            sidemenu_Panel.add(new transaksiPanel(this));   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base_panelRound = new Pallete.PanelRound();
        left_panelRound = new Pallete.PanelRound();
        logo_panelRound = new Pallete.PanelRound();
        literastis_Label = new javax.swing.JLabel();
        logo_Label = new javax.swing.JLabel();
        menu_panelRound = new Pallete.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        sidemenu_Panel = new javax.swing.JPanel();
        right_panelRound = new Pallete.PanelRound();
        navbar_panelRound = new Pallete.PanelRound();
        closebtn_Label = new javax.swing.JLabel();
        navbar_Panel = new javax.swing.JPanel();
        profile_panelRound = new Pallete.PanelRound();
        pfname_Label = new javax.swing.JLabel();
        profile_Label = new javax.swing.JLabel();
        contentsection_panelRound = new Pallete.PanelRound();
        content_panelRound = new Pallete.PanelRound();
        date_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        base_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        base_panelRound.setRoundBottomLeft(20);
        base_panelRound.setRoundBottomRight(20);
        base_panelRound.setRoundTopLeft(20);
        base_panelRound.setRoundTopRight(20);
        base_panelRound.setLayout(new java.awt.BorderLayout());

        left_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        left_panelRound.setPreferredSize(new java.awt.Dimension(200, 600));
        left_panelRound.setRoundBottomLeft(20);
        left_panelRound.setRoundTopLeft(20);
        left_panelRound.setLayout(new java.awt.BorderLayout());

        logo_panelRound.setBackground(new java.awt.Color(0, 255, 255));
        logo_panelRound.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        logo_panelRound.setPreferredSize(new java.awt.Dimension(200, 80));
        logo_panelRound.setRoundTopLeft(20);
        logo_panelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        literastis_Label.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        literastis_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        literastis_Label.setText("LITERASTIS");
        logo_panelRound.add(literastis_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 30));

        logo_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo (4).png"))); // NOI18N
        logo_panelRound.add(logo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 200, 50));

        left_panelRound.add(logo_panelRound, java.awt.BorderLayout.PAGE_START);

        menu_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        menu_panelRound.setRoundBottomLeft(20);

        jScrollPane1.setBorder(null);

        sidemenu_Panel.setBackground(new java.awt.Color(255, 255, 255));
        sidemenu_Panel.setLayout(new javax.swing.BoxLayout(sidemenu_Panel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(sidemenu_Panel);

        javax.swing.GroupLayout menu_panelRoundLayout = new javax.swing.GroupLayout(menu_panelRound);
        menu_panelRound.setLayout(menu_panelRoundLayout);
        menu_panelRoundLayout.setHorizontalGroup(
            menu_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        menu_panelRoundLayout.setVerticalGroup(
            menu_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        left_panelRound.add(menu_panelRound, java.awt.BorderLayout.CENTER);

        base_panelRound.add(left_panelRound, java.awt.BorderLayout.LINE_START);

        right_panelRound.setLayout(new java.awt.BorderLayout());

        navbar_panelRound.setBackground(new java.awt.Color(0, 255, 255));
        navbar_panelRound.setPreferredSize(new java.awt.Dimension(600, 80));
        navbar_panelRound.setRoundTopRight(20);

        closebtn_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vector.png"))); // NOI18N
        closebtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtn_LabelMouseClicked(evt);
            }
        });

        navbar_Panel.setBackground(new java.awt.Color(153, 255, 255));

        profile_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        profile_panelRound.setRoundBottomLeft(30);
        profile_panelRound.setRoundTopLeft(30);
        profile_panelRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_panelRoundMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_panelRoundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_panelRoundMouseExited(evt);
            }
        });

        pfname_Label.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        pfname_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pfname_Label.setText("Admin");
        pfname_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        profile_Label.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        profile_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconamoon_profile-circle-fill.png"))); // NOI18N
        profile_Label.setText("Profile Name");

        javax.swing.GroupLayout profile_panelRoundLayout = new javax.swing.GroupLayout(profile_panelRound);
        profile_panelRound.setLayout(profile_panelRoundLayout);
        profile_panelRoundLayout.setHorizontalGroup(
            profile_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelRoundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pfname_Label)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(profile_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelRoundLayout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(profile_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        profile_panelRoundLayout.setVerticalGroup(
            profile_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pfname_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addGroup(profile_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(profile_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbar_PanelLayout = new javax.swing.GroupLayout(navbar_Panel);
        navbar_Panel.setLayout(navbar_PanelLayout);
        navbar_PanelLayout.setHorizontalGroup(
            navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbar_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profile_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbar_PanelLayout.setVerticalGroup(
            navbar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbar_panelRoundLayout = new javax.swing.GroupLayout(navbar_panelRound);
        navbar_panelRound.setLayout(navbar_panelRoundLayout);
        navbar_panelRoundLayout.setHorizontalGroup(
            navbar_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbar_panelRoundLayout.createSequentialGroup()
                .addContainerGap(579, Short.MAX_VALUE)
                .addComponent(closebtn_Label)
                .addContainerGap())
            .addComponent(navbar_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navbar_panelRoundLayout.setVerticalGroup(
            navbar_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar_panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closebtn_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navbar_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        right_panelRound.add(navbar_panelRound, java.awt.BorderLayout.PAGE_START);

        contentsection_panelRound.setRoundBottomRight(20);

        content_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        content_panelRound.setRoundBottomLeft(20);
        content_panelRound.setRoundBottomRight(20);
        content_panelRound.setRoundTopLeft(20);
        content_panelRound.setRoundTopRight(20);
        content_panelRound.setLayout(new java.awt.BorderLayout());

        date_Label.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        date_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout contentsection_panelRoundLayout = new javax.swing.GroupLayout(contentsection_panelRound);
        contentsection_panelRound.setLayout(contentsection_panelRoundLayout);
        contentsection_panelRoundLayout.setHorizontalGroup(
            contentsection_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentsection_panelRoundLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(date_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentsection_panelRoundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(content_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentsection_panelRoundLayout.setVerticalGroup(
            contentsection_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentsection_panelRoundLayout.createSequentialGroup()
                .addComponent(date_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        right_panelRound.add(contentsection_panelRound, java.awt.BorderLayout.CENTER);

        base_panelRound.add(right_panelRound, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base_panelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(base_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx , y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void closebtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtn_LabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closebtn_LabelMouseClicked

    private void profile_panelRoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panelRoundMouseClicked
        // TODO add your handling code here:
        profile_panelRound.setBackground(new Color(215, 215, 215));
        
        profile_Dialog menu = new profile_Dialog(this, true, this);
        Point p = profile_panelRound.getLocationOnScreen();
        int x = p.x + profile_panelRound.getWidth() - menu.getWidth();
        int y = p.y + profile_panelRound.getHeight();
        menu.setLocation(x, y);
        menu.setVisible(true);
    }//GEN-LAST:event_profile_panelRoundMouseClicked

    private void profile_panelRoundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panelRoundMouseEntered
        // TODO add your handling code here:
        profile_panelRound.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_profile_panelRoundMouseEntered

    private void profile_panelRoundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_panelRoundMouseExited
        // TODO add your handling code here:
        profile_panelRound.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_profile_panelRoundMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        content_panelRound.removeAll();
        content_panelRound.add(new menuDashboard());
        content_panelRound.repaint();
        content_panelRound.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String userID = "ID";
                String levelUser = "Level";
                String namaUser = "Nama";
                
                new Menu(userID, namaUser, levelUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Pallete.PanelRound base_panelRound;
    private javax.swing.JLabel closebtn_Label;
    private Pallete.PanelRound content_panelRound;
    private Pallete.PanelRound contentsection_panelRound;
    private javax.swing.JLabel date_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private Pallete.PanelRound left_panelRound;
    private javax.swing.JLabel literastis_Label;
    private javax.swing.JLabel logo_Label;
    private Pallete.PanelRound logo_panelRound;
    private Pallete.PanelRound menu_panelRound;
    private javax.swing.JPanel navbar_Panel;
    private Pallete.PanelRound navbar_panelRound;
    private javax.swing.JLabel pfname_Label;
    private javax.swing.JLabel profile_Label;
    private Pallete.PanelRound profile_panelRound;
    private Pallete.PanelRound right_panelRound;
    private javax.swing.JPanel sidemenu_Panel;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        time = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                Calendar calendar = Calendar.getInstance();
                Date now = new Date();
                SimpleDateFormat formathari = new SimpleDateFormat("EEEE", new Locale("id","ID"));
                SimpleDateFormat formattanggal = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                String hari = formathari.format(calendar.getTime());
                String waktutanggal = formattanggal.format(now);
                date_Label.setText(hari+", "+waktutanggal);
            }
        });
        
        time.start();
    }
}
