/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.AnggotaController;
import Model.Anggota;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author laure
 */
public class menuAnggota extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    
    private AnggotaController controller;
    
    public menuAnggota() {
        initComponents();
        
        Anggota model = new Anggota();
        controller = new AnggotaController(model);
        setTableModel(controller.getAnggotaTableModel());
        
        delete_Button.setVisible(false);
        cancel_Button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jk_buttonGroup = new javax.swing.ButtonGroup();
        viewanggota_mainPanel = new javax.swing.JPanel();
        viewanggota_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        riwayat_Table = new javax.swing.JTable();
        dataanggota_Label = new javax.swing.JLabel();
        menuanggota_Label = new javax.swing.JLabel();
        anggota_Label = new javax.swing.JLabel();
        add_Label = new javax.swing.JLabel();
        add_Button = new javax.swing.JButton();
        delete_Label = new javax.swing.JLabel();
        delete_Button = new javax.swing.JButton();
        cancel_Label = new javax.swing.JLabel();
        cancel_Button = new javax.swing.JButton();
        search_Label = new javax.swing.JLabel();
        search_TextField = new javax.swing.JTextField();
        viewanggota_addPanel = new javax.swing.JPanel();
        dataanggota_Label1 = new javax.swing.JLabel();
        menuanggota_Label2 = new javax.swing.JLabel();
        anggota_Label1 = new javax.swing.JLabel();
        save_Label = new javax.swing.JLabel();
        save_Button = new javax.swing.JButton();
        batal_Label = new javax.swing.JLabel();
        batal_Button = new javax.swing.JButton();
        id_Label = new javax.swing.JLabel();
        id_TextField = new javax.swing.JTextField();
        nama_Label = new javax.swing.JLabel();
        nama_TextField = new javax.swing.JTextField();
        email_Label = new javax.swing.JLabel();
        email_TextField = new javax.swing.JTextField();
        telepon_Label = new javax.swing.JLabel();
        telepon_TextField = new javax.swing.JTextField();
        jk_Label = new javax.swing.JLabel();
        pria_RadioButton = new javax.swing.JRadioButton();
        wanita_RadioButton = new javax.swing.JRadioButton();
        tanggalgabung_Label = new javax.swing.JLabel();
        tanggalgabung_TextField = new javax.swing.JTextField();

        dateChooser1.setTextRefernce(tanggalgabung_TextField);

        setPreferredSize(new java.awt.Dimension(561, 480));
        setLayout(new java.awt.CardLayout());

        viewanggota_mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewanggota_mainPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewanggota_mainPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewanggota_mainPanel.setLayout(new java.awt.CardLayout());

        viewanggota_Panel.setBackground(new java.awt.Color(255, 255, 255));
        viewanggota_Panel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewanggota_Panel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewanggota_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riwayat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        riwayat_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayat_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(riwayat_Table);

        viewanggota_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 520, 310));

        dataanggota_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dataanggota_Label.setText("Data Anggota");
        viewanggota_Panel.add(dataanggota_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        menuanggota_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuanggota_Label.setText("Anggota");
        viewanggota_Panel.add(menuanggota_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        anggota_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lets-icons_group (1).png"))); // NOI18N
        viewanggota_Panel.add(anggota_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        add_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_add.png"))); // NOI18N
        viewanggota_Panel.add(add_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        add_Button.setBackground(new java.awt.Color(0, 0, 0));
        add_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        add_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_Button.setText("       Tambah");
        add_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ButtonActionPerformed(evt);
            }
        });
        viewanggota_Panel.add(add_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        delete_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_delete-outline.png"))); // NOI18N
        viewanggota_Panel.add(delete_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 30));

        delete_Button.setBackground(new java.awt.Color(255, 0, 0));
        delete_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_Button.setText("       Hapus");
        delete_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });
        viewanggota_Panel.add(delete_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 30));

        cancel_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewanggota_Panel.add(cancel_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 30));

        cancel_Button.setBackground(new java.awt.Color(255, 102, 0));
        cancel_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cancel_Button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_Button.setText("       Cancel");
        cancel_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });
        viewanggota_Panel.add(cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, 30));

        search_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_search.png"))); // NOI18N
        viewanggota_Panel.add(search_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, 30));

        search_TextField.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        search_TextField.setText("Search");
        search_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_TextFieldKeyTyped(evt);
            }
        });
        viewanggota_Panel.add(search_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 520, 30));

        viewanggota_mainPanel.add(viewanggota_Panel, "card3");

        viewanggota_addPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewanggota_addPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewanggota_addPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewanggota_addPanel.setPreferredSize(new java.awt.Dimension(561, 480));
        viewanggota_addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataanggota_Label1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dataanggota_Label1.setText("Tambah Data Anggota");
        viewanggota_addPanel.add(dataanggota_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        menuanggota_Label2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuanggota_Label2.setText("Anggota");
        viewanggota_addPanel.add(menuanggota_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        anggota_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lets-icons_group (1).png"))); // NOI18N
        viewanggota_addPanel.add(anggota_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        save_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tdesign_save.png"))); // NOI18N
        viewanggota_addPanel.add(save_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        save_Button.setBackground(new java.awt.Color(0, 51, 255));
        save_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        save_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_Button.setText("       Simpan");
        save_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        save_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ButtonActionPerformed(evt);
            }
        });
        viewanggota_addPanel.add(save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        batal_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewanggota_addPanel.add(batal_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 30));

        batal_Button.setBackground(new java.awt.Color(255, 102, 0));
        batal_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        batal_Button.setForeground(new java.awt.Color(255, 255, 255));
        batal_Button.setText("       Batal");
        batal_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        batal_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        batal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_ButtonActionPerformed(evt);
            }
        });
        viewanggota_addPanel.add(batal_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 30));

        id_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        id_Label.setText("ID");
        viewanggota_addPanel.add(id_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        id_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        id_TextField.setForeground(new java.awt.Color(102, 102, 102));
        id_TextField.setText("ID Anggota");
        viewanggota_addPanel.add(id_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 30));

        nama_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        nama_Label.setText("Nama");
        viewanggota_addPanel.add(nama_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        nama_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama_TextField.setForeground(new java.awt.Color(102, 102, 102));
        nama_TextField.setText("Nama Anggota");
        viewanggota_addPanel.add(nama_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 240, 30));

        email_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        email_Label.setText("Email");
        viewanggota_addPanel.add(email_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        email_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        email_TextField.setForeground(new java.awt.Color(102, 102, 102));
        email_TextField.setText("Email");
        viewanggota_addPanel.add(email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, 30));

        telepon_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        telepon_Label.setText("Telepon");
        viewanggota_addPanel.add(telepon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        telepon_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        telepon_TextField.setForeground(new java.awt.Color(102, 102, 102));
        telepon_TextField.setText("No. Telepon");
        viewanggota_addPanel.add(telepon_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 30));

        jk_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jk_Label.setText("Jenis Kelamin");
        viewanggota_addPanel.add(jk_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jk_buttonGroup.add(pria_RadioButton);
        pria_RadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pria_RadioButton.setText("Laki-Laki");
        viewanggota_addPanel.add(pria_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 70, -1));

        jk_buttonGroup.add(wanita_RadioButton);
        wanita_RadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        wanita_RadioButton.setText("Perempuan");
        viewanggota_addPanel.add(wanita_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, 20));

        tanggalgabung_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tanggalgabung_Label.setText("Tanggal Bergabung");
        viewanggota_addPanel.add(tanggalgabung_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        tanggalgabung_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tanggalgabung_TextField.setForeground(new java.awt.Color(102, 102, 102));
        viewanggota_addPanel.add(tanggalgabung_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, 30));

        viewanggota_mainPanel.add(viewanggota_addPanel, "card3");

        add(viewanggota_mainPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
        // TODO add your handling code here:
        viewanggota_mainPanel.removeAll();
        viewanggota_mainPanel.add(viewanggota_addPanel);
        viewanggota_mainPanel.repaint();
        viewanggota_mainPanel.revalidate();
        id_TextField.setEnabled(false);
        
        id_TextField.setText(controller.generateIDAnggota());
        if(add_Button.getText().equals("      Perbarui")){
            dataTabel();
            save_Button.setText("      Perbarui");
        }
    }//GEN-LAST:event_add_ButtonActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = riwayat_Table.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus data ini ?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String id = riwayat_Table.getValueAt(selectedRow, 0).toString();
            if (controller.deleteAnggota(id)) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
            }
        }
        resetForm();
        delete_Button.setVisible(false);
        cancel_Button.setVisible(false);
        showPanel();
    }//GEN-LAST:event_delete_ButtonActionPerformed

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        // TODO add your handling code here:
        showPanel();
        delete_Button.setVisible(false);
        cancel_Button.setVisible(false);
    }//GEN-LAST:event_cancel_ButtonActionPerformed

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
        // TODO add your handling code here:
        if (save_Button.getText() == "Tambah") {
            save_Button.setText("       Simpan");
        } else if (save_Button.getText() == "       Simpan") {
            insertData();
        } else if (save_Button.getText() == "      Perbarui") {
            updateData();
        }
    }//GEN-LAST:event_save_ButtonActionPerformed

    private void batal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_ButtonActionPerformed
        // TODO add your handling code here:
        viewanggota_mainPanel.removeAll();
        viewanggota_mainPanel.add(viewanggota_Panel);
        viewanggota_mainPanel.repaint();
        viewanggota_mainPanel.revalidate();
        resetForm();
    }//GEN-LAST:event_batal_ButtonActionPerformed

    private void riwayat_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayat_TableMouseClicked
        // TODO add your handling code here:
        if (add_Button.getText().equals("       Tambah")){
            add_Button.setText("      Perbarui");
            delete_Button.setVisible(true);
            cancel_Button.setVisible(true);
        }   
    }//GEN-LAST:event_riwayat_TableMouseClicked

    private void search_TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_TextFieldKeyTyped
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_search_TextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Button;
    private javax.swing.JLabel add_Label;
    private javax.swing.JLabel anggota_Label;
    private javax.swing.JLabel anggota_Label1;
    private javax.swing.JButton batal_Button;
    private javax.swing.JLabel batal_Label;
    private javax.swing.JButton cancel_Button;
    private javax.swing.JLabel cancel_Label;
    private javax.swing.JLabel dataanggota_Label;
    private javax.swing.JLabel dataanggota_Label1;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton delete_Button;
    private javax.swing.JLabel delete_Label;
    private javax.swing.JLabel email_Label;
    private javax.swing.JTextField email_TextField;
    private javax.swing.JLabel id_Label;
    private javax.swing.JTextField id_TextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jk_Label;
    private javax.swing.ButtonGroup jk_buttonGroup;
    private javax.swing.JLabel menuanggota_Label;
    private javax.swing.JLabel menuanggota_Label2;
    private javax.swing.JLabel nama_Label;
    private javax.swing.JTextField nama_TextField;
    private javax.swing.JRadioButton pria_RadioButton;
    private javax.swing.JTable riwayat_Table;
    private javax.swing.JButton save_Button;
    private javax.swing.JLabel save_Label;
    private javax.swing.JLabel search_Label;
    private javax.swing.JTextField search_TextField;
    private javax.swing.JLabel tanggalgabung_Label;
    private javax.swing.JTextField tanggalgabung_TextField;
    private javax.swing.JLabel telepon_Label;
    private javax.swing.JTextField telepon_TextField;
    private javax.swing.JPanel viewanggota_Panel;
    private javax.swing.JPanel viewanggota_addPanel;
    private javax.swing.JPanel viewanggota_mainPanel;
    private javax.swing.JRadioButton wanita_RadioButton;
    // End of variables declaration//GEN-END:variables

    private void setTableModel(DefaultTableModel model) {
        riwayat_Table.setModel(model);
    }
    
    private void resetForm() {
        nama_TextField.setText("Nama Anggota");
        email_TextField.setText("Email");
        telepon_TextField.setText("No. Telepon");
        tanggalgabung_TextField.setText("");
        jk_buttonGroup.clearSelection();
    }
    
    private void showPanel(){
        viewanggota_mainPanel.removeAll();
        viewanggota_mainPanel.add(new menuAnggota());
        viewanggota_mainPanel.repaint();
        viewanggota_mainPanel.revalidate();
    }

    private void insertData() {
        String namaAnggota = nama_TextField.getText();
        String emailAnggota = email_TextField.getText();
        String teleponAnggota = telepon_TextField.getText();
        String jkAnggota = pria_RadioButton.isSelected() ? pria_RadioButton.getText() : wanita_RadioButton.getText();
        String tglAnggota = tanggalgabung_TextField.getText();

        if (namaAnggota.isEmpty() || emailAnggota.isEmpty() || teleponAnggota.isEmpty() || jkAnggota.isEmpty() || tglAnggota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom harus diisi !", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (controller.addAnggota(namaAnggota, emailAnggota, teleponAnggota, tglAnggota, jkAnggota)) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
            resetForm();
            delete_Button.setVisible(false);
            cancel_Button.setVisible(false);
            showPanel();
        }
    }

    private void dataTabel() {
        viewanggota_Panel.setVisible(false);
        viewanggota_addPanel.setVisible(true);
        
        int row = riwayat_Table.getSelectedRow();
        dataanggota_Label1.setText("Perbarui Data Anggota");
        
        id_TextField.setEnabled(false);
        tanggalgabung_TextField.setEnabled(false);
        
        id_TextField.setText(riwayat_Table.getValueAt(row, 0).toString());
        nama_TextField.setText(riwayat_Table.getValueAt(row, 1).toString());
        email_TextField.setText(riwayat_Table.getValueAt(row, 2).toString());
        telepon_TextField.setText(riwayat_Table.getValueAt(row, 3).toString());
        
        String jk = riwayat_Table.getValueAt(row, 5).toString();
            if (jk.equals("Laki-Laki")){
                pria_RadioButton.setSelected(true);
            } else if(jk.equals("Perempuan")){
                wanita_RadioButton.setSelected(true);
            }
            
        tanggalgabung_TextField.setText(riwayat_Table.getValueAt(row, 4).toString());
    }

    private void updateData() {
        String idAnggota = id_TextField.getText();
        String namaAnggota = nama_TextField.getText();
        String emailAnggota = email_TextField.getText();
        String teleponAnggota = telepon_TextField.getText();
        String jkAnggota = pria_RadioButton.isSelected() ? pria_RadioButton.getText() : wanita_RadioButton.getText();
        String tglAnggota = tanggalgabung_TextField.getText();

        if (idAnggota.isEmpty() || namaAnggota.isEmpty() || emailAnggota.isEmpty() || teleponAnggota.isEmpty() || jkAnggota.isEmpty() || tglAnggota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom harus diisi !", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (controller.updateAnggota(idAnggota, namaAnggota, emailAnggota, teleponAnggota, tglAnggota, jkAnggota)) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui");
            resetForm();
            delete_Button.setVisible(false);
            cancel_Button.setVisible(false);
            showPanel();
        }
    }

    private void searchData() {
        DefaultTableModel model = controller.searchAnggota(search_TextField.getText());
        riwayat_Table.setModel(model);
    }
}
