/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.Koneksi;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author laure
 */
public class menuLaporan extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    private final Connection conn;
    private Date tanggalMulai;
    private Date tanggalAkhir;
    
    public menuLaporan() {
        initComponents();
        
        conn = Koneksi.getConnection();
        setTableModel();
        print_Button.setVisible(false);
        cancel_Button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser2 = new com.raven.datechooser.DateChooser();
        dateChooser3 = new com.raven.datechooser.DateChooser();
        viewreport_mainPanel = new javax.swing.JPanel();
        viewreport_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        riwayat_Table = new javax.swing.JTable();
        reportbuku_Label = new javax.swing.JLabel();
        laporan_Label = new javax.swing.JLabel();
        report_Label = new javax.swing.JLabel();
        display_Label = new javax.swing.JLabel();
        display_Button = new javax.swing.JButton();
        print_Label = new javax.swing.JLabel();
        print_Button = new javax.swing.JButton();
        cancel_Label = new javax.swing.JLabel();
        cancel_Button = new javax.swing.JButton();
        tanggalmulai_Label = new javax.swing.JLabel();
        tanggalmulai_TextField = new javax.swing.JTextField();
        tanggalakhir_Label = new javax.swing.JLabel();
        tanggalakhir_TextField = new javax.swing.JTextField();

        dateChooser2.setTextRefernce(tanggalmulai_TextField);

        dateChooser3.setTextRefernce(tanggalakhir_TextField);

        setPreferredSize(new java.awt.Dimension(561, 480));
        setLayout(new java.awt.CardLayout());

        viewreport_mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewreport_mainPanel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewreport_mainPanel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewreport_mainPanel.setLayout(new java.awt.CardLayout());

        viewreport_Panel.setBackground(new java.awt.Color(255, 255, 255));
        viewreport_Panel.setMaximumSize(new java.awt.Dimension(561, 480));
        viewreport_Panel.setMinimumSize(new java.awt.Dimension(561, 480));
        viewreport_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riwayat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(riwayat_Table);

        viewreport_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 520, 270));

        reportbuku_Label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        reportbuku_Label.setText("Laporan Peminjaman Buku");
        viewreport_Panel.add(reportbuku_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, -1, 35));

        laporan_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        laporan_Label.setText("Laporan");
        viewreport_Panel.add(laporan_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        report_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_file-report-outline.png"))); // NOI18N
        viewreport_Panel.add(report_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, -1, -1));

        display_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-park-outline_add.png"))); // NOI18N
        viewreport_Panel.add(display_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        display_Button.setBackground(new java.awt.Color(0, 0, 0));
        display_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        display_Button.setForeground(new java.awt.Color(255, 255, 255));
        display_Button.setText("        Tampilkan");
        display_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        display_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        display_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_ButtonActionPerformed(evt);
            }
        });
        viewreport_Panel.add(display_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));

        print_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_delete-outline.png"))); // NOI18N
        viewreport_Panel.add(print_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 30));

        print_Button.setBackground(new java.awt.Color(51, 102, 255));
        print_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        print_Button.setForeground(new java.awt.Color(255, 255, 255));
        print_Button.setText("      Cetak");
        print_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        print_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_ButtonActionPerformed(evt);
            }
        });
        viewreport_Panel.add(print_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, 30));

        cancel_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabler_clock-cancel.png"))); // NOI18N
        viewreport_Panel.add(cancel_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 30));

        cancel_Button.setBackground(new java.awt.Color(255, 102, 0));
        cancel_Button.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        cancel_Button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_Button.setText("       Cancel");
        cancel_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_Button.setPreferredSize(new java.awt.Dimension(60, 26));
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });
        viewreport_Panel.add(cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, 30));

        tanggalmulai_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tanggalmulai_Label.setText("Tanggal Mulai");
        viewreport_Panel.add(tanggalmulai_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        tanggalmulai_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tanggalmulai_TextField.setForeground(new java.awt.Color(102, 102, 102));
        viewreport_Panel.add(tanggalmulai_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 30));

        tanggalakhir_Label.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tanggalakhir_Label.setText("Tanggal Selesai");
        viewreport_Panel.add(tanggalakhir_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        tanggalakhir_TextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tanggalakhir_TextField.setForeground(new java.awt.Color(102, 102, 102));
        viewreport_Panel.add(tanggalakhir_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, 30));

        viewreport_mainPanel.add(viewreport_Panel, "card3");

        add(viewreport_mainPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void display_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_ButtonActionPerformed
        // TODO add your handling code here:
        loadData();
        print_Button.setVisible(true);
        cancel_Button.setVisible(true);
    }//GEN-LAST:event_display_ButtonActionPerformed

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        // TODO add your handling code here:
        showPanel();
        loadData();
    }//GEN-LAST:event_cancel_ButtonActionPerformed

    private void print_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_ButtonActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_print_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_Button;
    private javax.swing.JLabel cancel_Label;
    private com.raven.datechooser.DateChooser dateChooser2;
    private com.raven.datechooser.DateChooser dateChooser3;
    private javax.swing.JButton display_Button;
    private javax.swing.JLabel display_Label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laporan_Label;
    private javax.swing.JButton print_Button;
    private javax.swing.JLabel print_Label;
    private javax.swing.JLabel report_Label;
    private javax.swing.JLabel reportbuku_Label;
    private javax.swing.JTable riwayat_Table;
    private javax.swing.JLabel tanggalakhir_Label;
    private javax.swing.JTextField tanggalakhir_TextField;
    private javax.swing.JLabel tanggalmulai_Label;
    private javax.swing.JTextField tanggalmulai_TextField;
    private javax.swing.JPanel viewreport_Panel;
    private javax.swing.JPanel viewreport_mainPanel;
    // End of variables declaration//GEN-END:variables

    private void setTableModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengembalian");
        model.addColumn("ID Anggota");
        model.addColumn("Nama Anggota");
        model.addColumn("ID_Buku");
        model.addColumn("Tanggal Peminjaman");
        model.addColumn("Tanggal Pengembalian");
        model.addColumn("Status Peminjaman");
        model.addColumn("Jumlah Denda");

        riwayat_Table.setModel(model);
    }

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) riwayat_Table.getModel();
        print_Button.setVisible(false);
        cancel_Button.setVisible(false);
        model.setRowCount(0);

        String tanggalMulai = tanggalmulai_TextField.getText();
        String tanggalAkhir = tanggalakhir_TextField.getText();

        String sql = "SELECT Pengembalian.ID_Pengembalian, Anggota.ID_Anggota, Nama_Anggota, Buku.ID_Buku, Tanggal_Peminjaman, Peminjaman.Tanggal_Pengembalian, Status_Peminjaman, Jumlah_Denda "
                   + "FROM Pengembalian "
                   + "INNER JOIN Detail_Pengembalian ON Detail_Pengembalian.ID_Pengembalian = Pengembalian.ID_Pengembalian "
                   + "INNER JOIN Peminjaman ON Peminjaman.ID_Peminjaman = Pengembalian.ID_Peminjaman "
                   + "INNER JOIN Detail_Peminjaman ON Detail_Peminjaman.ID_Peminjaman = Peminjaman.ID_Peminjaman "
                   + "INNER JOIN Buku ON Buku.ID_Buku = Detail_Peminjaman.ID_Buku "
                   + "INNER JOIN Anggota ON Anggota.ID_Anggota = Peminjaman.ID_Anggota "
                   + "WHERE Peminjaman.Tanggal_Peminjaman BETWEEN ? AND ? AND Detail_Peminjaman.Status_Peminjaman = 'Sudah dikembalikan' "
                   + "GROUP BY Buku.ID_Buku, Peminjaman.ID_Peminjaman, Pengembalian.ID_Pengembalian, Peminjaman.Tanggal_Peminjaman "
                   + "ORDER BY Pengembalian.ID_Pengembalian ASC";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, tanggalMulai);
            st.setString(2, tanggalAkhir);
            
            try (ResultSet rs = st.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("ID_Pengembalian"), rs.getString("ID_Anggota"), rs.getString("Nama_Anggota"), rs.getString("ID_Buku"), rs.getString("Tanggal_Peminjaman"), rs.getString("Tanggal_Pengembalian"), rs.getString("Status_Peminjaman"), rs.getString("Jumlah_Denda")});
                }
            }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(menuLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }
    
    private void resetForm() {
        
    }
    
    private void showPanel(){
        viewreport_mainPanel.removeAll();
        viewreport_mainPanel.add(new menuLaporan());
        viewreport_mainPanel.repaint();
        viewreport_mainPanel.revalidate();
    }

    private void print() {
        String tanggalMulai = tanggalmulai_TextField.getText();
        String tanggalAkhir = tanggalakhir_TextField.getText();

        try {
            // Pastikan jalur file sesuai dengan struktur proyek Anda
            String reportPath = "src/Reports/laporanPeminjaman1.jasper";

            // Periksa apakah file laporan ada
            File reportFile = new File(reportPath);
            if (!reportFile.exists()) {
                throw new JRException("File report tidak ditemukan: " + reportPath);
            }

            // Siapkan parameter untuk laporan
            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("tanggalMulai", tanggalMulai);
            parameters.put("tanggalAkhir", tanggalAkhir);

            // Isi laporan dengan data dari database
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
            viewer.setVisible(true);

        } catch (JRException e) {
            e.printStackTrace();
            // Anda bisa menampilkan pesan error ke pengguna, misalnya menggunakan dialog
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencetak laporan: " + e.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }

}
