/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author laure
 */
public class profile_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form profile_Dialog
     */
    
    private Menu menuUtama;
    
    public profile_Dialog(java.awt.Frame parent, boolean modal, Menu menuUtama) {
        super(parent, modal);
        initComponents();
        this.menuUtama = menuUtama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acc_panelRound = new Pallete.PanelRound();
        pass_Panel = new javax.swing.JPanel();
        pass_Label = new javax.swing.JLabel();
        passbtn_Label = new javax.swing.JLabel();
        line_panelRound7 = new Pallete.PanelRound();
        logout_Panel = new javax.swing.JPanel();
        logout_Label = new javax.swing.JLabel();
        logoutbtn_Label = new javax.swing.JLabel();
        line_panelRound8 = new Pallete.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        acc_panelRound.setBackground(new java.awt.Color(255, 255, 255));
        acc_panelRound.setRoundBottomLeft(20);
        acc_panelRound.setRoundBottomRight(20);
        acc_panelRound.setRoundTopLeft(20);
        acc_panelRound.setRoundTopRight(20);

        pass_Panel.setBackground(new java.awt.Color(255, 255, 255));

        pass_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vaadin_password.png"))); // NOI18N

        passbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passbtn_Label.setText("Pergantian Password");
        passbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound7.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound7.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound7Layout = new javax.swing.GroupLayout(line_panelRound7);
        line_panelRound7.setLayout(line_panelRound7Layout);
        line_panelRound7Layout.setHorizontalGroup(
            line_panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound7Layout.setVerticalGroup(
            line_panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pass_PanelLayout = new javax.swing.GroupLayout(pass_Panel);
        pass_Panel.setLayout(pass_PanelLayout);
        pass_PanelLayout.setHorizontalGroup(
            pass_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pass_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passbtn_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pass_PanelLayout.setVerticalGroup(
            pass_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
            .addComponent(pass_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
            .addComponent(passbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logout_Panel.setBackground(new java.awt.Color(255, 255, 255));

        logout_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/material-symbols_logout.png"))); // NOI18N

        logoutbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logoutbtn_Label.setText("Logout");
        logoutbtn_Label.setPreferredSize(new java.awt.Dimension(123, 16));
        logoutbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound8.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound8.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound8Layout = new javax.swing.GroupLayout(line_panelRound8);
        line_panelRound8.setLayout(line_panelRound8Layout);
        line_panelRound8Layout.setHorizontalGroup(
            line_panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound8Layout.setVerticalGroup(
            line_panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout logout_PanelLayout = new javax.swing.GroupLayout(logout_Panel);
        logout_Panel.setLayout(logout_PanelLayout);
        logout_PanelLayout.setHorizontalGroup(
            logout_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutbtn_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logout_PanelLayout.setVerticalGroup(
            logout_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(logout_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(logoutbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout acc_panelRoundLayout = new javax.swing.GroupLayout(acc_panelRound);
        acc_panelRound.setLayout(acc_panelRoundLayout);
        acc_panelRoundLayout.setHorizontalGroup(
            acc_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acc_panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(acc_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pass_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        acc_panelRoundLayout.setVerticalGroup(
            acc_panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acc_panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pass_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(acc_panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acc_panelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passbtn_LabelMouseClicked
        // TODO add your handling code here:
        pass_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound7.setBackground(new Color(0, 0, 0));
        
        dispose();
        JPanel jp = menuUtama.getPanelUtama();
        LoginView login = new LoginView();
        menuPassword formgantipass = new menuPassword();
        
        jp.removeAll();
        jp.add(formgantipass);
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_passbtn_LabelMouseClicked

    private void passbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passbtn_LabelMouseEntered
        // TODO add your handling code here:
        pass_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound7.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_passbtn_LabelMouseEntered

    private void passbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passbtn_LabelMouseExited
        // TODO add your handling code here:
        pass_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound7.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_passbtn_LabelMouseExited

    private void logoutbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn_LabelMouseClicked
        // TODO add your handling code here:
        logout_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound8.setBackground(new Color(0, 0, 0));
        
        dispose();
        menuUtama.dispose();
        LoginView login = new LoginView();
        login.setVisible(true);
    }//GEN-LAST:event_logoutbtn_LabelMouseClicked

    private void logoutbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn_LabelMouseEntered
        // TODO add your handling code here:
        logout_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound8.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_logoutbtn_LabelMouseEntered

    private void logoutbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn_LabelMouseExited
        // TODO add your handling code here:
        logout_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound8.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_logoutbtn_LabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                profile_Dialog dialog = new profile_Dialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Pallete.PanelRound acc_panelRound;
    private Pallete.PanelRound line_panelRound7;
    private Pallete.PanelRound line_panelRound8;
    private javax.swing.JLabel logout_Label;
    private javax.swing.JPanel logout_Panel;
    private javax.swing.JLabel logoutbtn_Label;
    private javax.swing.JLabel pass_Label;
    private javax.swing.JPanel pass_Panel;
    private javax.swing.JLabel passbtn_Label;
    // End of variables declaration//GEN-END:variables
}
