/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author laure
 */
public class transaksiPanel extends javax.swing.JPanel {

    /**
     * Creates new form transaksiPanel
     */
    
    private Menu menuUtama;
    
    public transaksiPanel(Menu menuUtama) {
        initComponents();
        this.menuUtama = menuUtama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaksi_Label = new javax.swing.JLabel();
        pengembalian_Panel = new javax.swing.JPanel();
        pengembalian_Label = new javax.swing.JLabel();
        pengembalianbtn_Label = new javax.swing.JLabel();
        line_panelRound6 = new Pallete.PanelRound();
        peminjaman_Panel = new javax.swing.JPanel();
        peminjaman_Label = new javax.swing.JLabel();
        peminjamanbtn_Label = new javax.swing.JLabel();
        line_panelRound4 = new Pallete.PanelRound();
        laporan_Label = new javax.swing.JLabel();
        laporan_Panel = new javax.swing.JPanel();
        laporanpeminjaman_Label = new javax.swing.JLabel();
        laporanbtn_Label = new javax.swing.JLabel();
        line_panelRound7 = new Pallete.PanelRound();

        setBackground(new java.awt.Color(255, 255, 255));

        transaksi_Label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        transaksi_Label.setForeground(new java.awt.Color(102, 102, 102));
        transaksi_Label.setText("TRANSAKSI");

        pengembalian_Panel.setBackground(new java.awt.Color(255, 255, 255));

        pengembalian_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lucide_book-up-2 (1).png"))); // NOI18N

        pengembalianbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pengembalianbtn_Label.setText("PENGEMBALIAN");
        pengembalianbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembalianbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengembalianbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengembalianbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound6.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound6Layout = new javax.swing.GroupLayout(line_panelRound6);
        line_panelRound6.setLayout(line_panelRound6Layout);
        line_panelRound6Layout.setHorizontalGroup(
            line_panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound6Layout.setVerticalGroup(
            line_panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pengembalian_PanelLayout = new javax.swing.GroupLayout(pengembalian_Panel);
        pengembalian_Panel.setLayout(pengembalian_PanelLayout);
        pengembalian_PanelLayout.setHorizontalGroup(
            pengembalian_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembalian_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pengembalian_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pengembalianbtn_Label)
                .addContainerGap())
        );
        pengembalian_PanelLayout.setVerticalGroup(
            pengembalian_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(pengembalian_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(pengembalianbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        peminjaman_Panel.setBackground(new java.awt.Color(255, 255, 255));
        peminjaman_Panel.setPreferredSize(new java.awt.Dimension(162, 47));

        peminjaman_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lucide_book-down (1).png"))); // NOI18N

        peminjamanbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        peminjamanbtn_Label.setText("PEMINJAMAN");
        peminjamanbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peminjamanbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peminjamanbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound4.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound4Layout = new javax.swing.GroupLayout(line_panelRound4);
        line_panelRound4.setLayout(line_panelRound4Layout);
        line_panelRound4Layout.setHorizontalGroup(
            line_panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound4Layout.setVerticalGroup(
            line_panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout peminjaman_PanelLayout = new javax.swing.GroupLayout(peminjaman_Panel);
        peminjaman_Panel.setLayout(peminjaman_PanelLayout);
        peminjaman_PanelLayout.setHorizontalGroup(
            peminjaman_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjaman_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peminjaman_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peminjamanbtn_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        peminjaman_PanelLayout.setVerticalGroup(
            peminjaman_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(peminjaman_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(peminjamanbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        laporan_Label.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        laporan_Label.setForeground(new java.awt.Color(102, 102, 102));
        laporan_Label.setText("LAPORAN");

        laporan_Panel.setBackground(new java.awt.Color(255, 255, 255));

        laporanpeminjaman_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mdi_file-report-outline.png"))); // NOI18N

        laporanbtn_Label.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        laporanbtn_Label.setText("PEMINJAMAN");
        laporanbtn_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanbtn_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanbtn_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanbtn_LabelMouseExited(evt);
            }
        });

        line_panelRound7.setBackground(new java.awt.Color(255, 255, 255));
        line_panelRound7.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout line_panelRound7Layout = new javax.swing.GroupLayout(line_panelRound7);
        line_panelRound7.setLayout(line_panelRound7Layout);
        line_panelRound7Layout.setHorizontalGroup(
            line_panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        line_panelRound7Layout.setVerticalGroup(
            line_panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout laporan_PanelLayout = new javax.swing.GroupLayout(laporan_Panel);
        laporan_Panel.setLayout(laporan_PanelLayout);
        laporan_PanelLayout.setHorizontalGroup(
            laporan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporan_PanelLayout.createSequentialGroup()
                .addComponent(line_panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laporanpeminjaman_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laporanbtn_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        laporan_PanelLayout.setVerticalGroup(
            laporan_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(line_panelRound7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(laporanpeminjaman_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(laporanbtn_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pengembalian_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peminjaman_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaksi_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(laporan_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laporan_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(transaksi_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peminjaman_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengembalian_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(laporan_Label)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(laporan_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pengembalianbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianbtn_LabelMouseClicked
        // TODO add your handling code here:
        pengembalian_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound6.setBackground(new Color(0, 0, 0));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuPengembalian(menuUtama.getUserID()));
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_pengembalianbtn_LabelMouseClicked

    private void pengembalianbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianbtn_LabelMouseEntered
        // TODO add your handling code here:
        pengembalian_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound6.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_pengembalianbtn_LabelMouseEntered

    private void pengembalianbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianbtn_LabelMouseExited
        // TODO add your handling code here:
        pengembalian_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pengembalianbtn_LabelMouseExited

    private void peminjamanbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanbtn_LabelMouseClicked
        // TODO add your handling code here:
        peminjaman_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound4.setBackground(new Color(0, 0, 0));
        
        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuPeminjaman(menuUtama.getUserID()));
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_peminjamanbtn_LabelMouseClicked

    private void peminjamanbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanbtn_LabelMouseEntered
        // TODO add your handling code here:
        peminjaman_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound4.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_peminjamanbtn_LabelMouseEntered

    private void peminjamanbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanbtn_LabelMouseExited
        // TODO add your handling code here:
        peminjaman_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_peminjamanbtn_LabelMouseExited

    private void laporanbtn_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanbtn_LabelMouseClicked
        // TODO add your handling code here:
        laporan_Panel.setBackground(new Color(215, 215, 215));
        line_panelRound7.setBackground(new Color(0, 0, 0));

        JPanel jp = menuUtama.getPanelUtama();
        jp.removeAll();
        jp.add(new menuLaporan());
        jp.repaint();
        jp.revalidate();
    }//GEN-LAST:event_laporanbtn_LabelMouseClicked

    private void laporanbtn_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanbtn_LabelMouseEntered
        // TODO add your handling code here:
        laporan_Panel.setBackground(new Color(235, 235, 235));
        line_panelRound7.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_laporanbtn_LabelMouseEntered

    private void laporanbtn_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanbtn_LabelMouseExited
        // TODO add your handling code here:
        laporan_Panel.setBackground(new Color(255, 255, 255));
        line_panelRound7.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_laporanbtn_LabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel laporan_Label;
    private javax.swing.JPanel laporan_Panel;
    private javax.swing.JLabel laporanbtn_Label;
    private javax.swing.JLabel laporanpeminjaman_Label;
    private Pallete.PanelRound line_panelRound4;
    private Pallete.PanelRound line_panelRound6;
    private Pallete.PanelRound line_panelRound7;
    private javax.swing.JLabel peminjaman_Label;
    private javax.swing.JPanel peminjaman_Panel;
    private javax.swing.JLabel peminjamanbtn_Label;
    private javax.swing.JLabel pengembalian_Label;
    private javax.swing.JPanel pengembalian_Panel;
    private javax.swing.JLabel pengembalianbtn_Label;
    private javax.swing.JLabel transaksi_Label;
    // End of variables declaration//GEN-END:variables
}
